icgc-argo/platform-ui

client/uikit/plopfile.js
No need to have `readme` or `test` in the create-component generate file
These can be added as the need arises
=> remove readme and test templates from component generate

client/.env.schema, client/global/config.js, client/global/utils/getApolloCacheForQueries.js, client/global/utils/runQuery.js, client/next.config.js, client/pages/_app.js, client/queryValidations.test.js
Changes name to be less generic
Updates `.env.schema` to use proper var
=> rename API_ROOT to GATEWAY_API_ROOT

server/schemas/Program/index.js, server/services/programService/index.js
There is a hack to deal with a peculiarity of the UpdateProgram service: Before calling update, we call GetProgram to find the current values. The call to UpdateProgram provides all those values for fields that are not desired to be overwritten.
Otherwise, normal gateway service patternz...
=> UpdateProgram in Gateway

client/components/pages/submission-system/program-management/Users.js, client/uikit/Modal/index.js
just refactored to use the standard modal implementation for ResendEmailModal which had its own thing before that messed with the modal storybook
=> use standard modal implementation for ResendEmailModal

client/uikit/AppBar/index.js
Storybook was breaking for the story because ref wasn't passed in. It shouldn't be a required prop anyway.
=> fix app bar menu item ref

client/components/pages/submission-system/toaster.js
Adds ability to add toast with custom timeout. `timeout` is available in `addToast` only and isn't added to the props fed to `ToastStack` component
=>  adds ability to add toast with custom timeout

client/components/pages/submission-system/SIDE_MENU_PROGRAM_LIST.gql, client/components/pages/submission-system/SideMenu.js, client/pages/submission/program/[shortName]/clinical-submission.js, client/pages/submission/program/[shortName]/dashboard.js, client/pages/submission/program/[shortName]/id-registration.js, client/pages/submission/program/[shortName]/manage.js, client/pages/submission/program/index.js
… side
Basically pre-resolve the `SIDE_MENU_PROGRAM_LIST` graphql query on the server side so browser doesn't have to. This would help with reducing the flashing of the side menu when navigating.
`getGqlQueriesToPrefetch` is something we always had, just never used.
=> SIDE_MENU_PROGRAM_LIST pre-render

uikit/Progress/index.js
this prevents the z-index from pushing the `::before` and `::after` to top of page
=> 🐛 adds transform to ProgressSection so z-index applies locally

components/ApplicationRoot.js, components/pages/submission-system/SideMenu.js, components/pages/submission-system/layout.js, components/pages/submission-system/program-management/ManageProgramTabs.js, global/hooks/usePersistentContext.js
- Add persistentContext, which contains an usePersistentState hook
that's pretty similar to React.useState except the state is persistent
across page navigations
- Persistent search string in the sidemenu
- Persistent programs in the sidemenu
- Persistent scrolling position of sidemenu
=> Persist state between page navigations

uikit/Icon/index.tsx
> If an element can be described by visible text, it is recommended to reference that text with an aria-labelledby attribute rather than using the <title> element.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
=> Use arial-labelledby to describe svg

components/pages/submission-system/SideMenu.tsx, components/pages/submission-system/program-sample-registration/index.tsx, uikit/SubMenu/index.tsx, uikit/SubMenu/styledComponents.tsx
Firefox version 60 in windows 10 does not support focusing on the input
of an button element
=> Fix input inside button which is not supported by an old Firefox version

components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx, components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx, components/pages/submission-system/program-clinical-submission/index.tsx
- fixes the funky error removal behaviour.
- uses index as the unique identifier for each error
- updates apollo cache directly instead of going through a local state (`fileError` is ephemeral so no need to worry about being out-of-sync from server-side)
- Hides the badge for each clinical entity when records count is 0
- Implements the success condition on each entity badge when the submission is validated (see https://github.com/icgc-argo/platform-ui/pull/752/commits/95230bf0bfb14077c170a33244ab04c23aaa54a6)
- Implements the purple star for new records (see https://github.com/icgc-argo/platform-ui/pull/752/commits/74c286c05d5dd8aedc658f7b1b66d0cf8313f8ba)
- Also updates logic to compare row to stats
=> Improvements on Clinical submission page

components/ApplicationRoot.tsx, components/NavBar.tsx, components/pages/login.tsx, components/pages/submission-system/common.tsx, components/pages/submission-system/program-sample-registration/Instructions/index.tsx, global/config.ts, global/hooks/useAuthContext.tsx, global/utils/egoJwt/index.tsx, global/utils/getApolloCacheForQueries.tsx, next.config.js, pages/_app.tsx
Using `env` in next-config requires the env vars to be injected at build-time, which @d8660091 provided some great arguments against :). This PR creates a custom wrap around `getConfig` that gives static types so envs are read at run time but accessed with type safety.
=> 🐛 fixes how env vars are accessed

components/pages/submission-system/program-sample-registration/REGISTRATION_FRAGMENT.gql, components/pages/submission-system/program-sample-registration/index.tsx
…al columns
Previously the stat counter was taking each individual change as a variable even if on same row eg.
new specimen [row 1] + new sample id [row 1] = 2 new files
changed to take rows into account
added `isNew` property to display this on FileTable 
=> Register sample stats, use rows instead of cols

components/pages/submission-system/program-clinical-submission/SignOffValidationModal.tsx, components/pages/submission-system/program-clinical-submission/index.tsx
- Modal content is slightly different for sign off with / without update
- Don't hide the spinner during sign off if going to redirect (next's redirect is async but somehow can't be awaited...)
=> 🐛 improves the signoff without update flow

components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx, components/pages/submission-system/program-clinical-submission/Header.tsx, components/pages/submission-system/program-clinical-submission/PageContent.tsx, components/pages/submission-system/program-clinical-submission/index.tsx
- splits up the index file into `Header` and `PageContent` components to keep @joneubank happy
- lifts the selected vertical tab state up from `FilesNavigator/index.tsx` to `PageContent`
- sets selected vertical tab after file upload, based on file name and priority (look for implementation and usage of `getDefaultClinicalEntityIndex`)
=> ✨ sets selected clinical submission after action

.huskyrc
Adds a git hook for type check before pushing. Why?
- informs devs of type issues before pushing --> don't have to actively monitor CI status on PRs
- why `pre-push`? because `pre-commit` is too much
- why not `npm run build`? because that takes even longer than a type check, and typically doesn't catch any more issue.
=> 👷 adds ts typecheck git push hook

components/pages/submission-system/common.tsx, components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx, components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- total row count should not be the sum of stats
- fade out stats before validation
- removes the stars from column before validation
- reorders the stats above the table
- implements sorting by the stars
=> 🐛 clinical submission stats fix

components/ApplicationRoot.tsx
We are getting multiple apollo clients created and trying to hook onto the dev tools which seems to confuse it. This ensures that only the final client gets to hook onto the dev tool.
=> 🐛 fixes apollo client initialization to work with dev tool

components/ApplicationRoot.tsx, components/pages/submission-system/program-clinical-submission/Header.tsx, components/pages/submission-system/program-clinical-submission/PageContent.tsx, components/pages/submission-system/program-clinical-submission/gql/CLINICAL_SUBMISSION_QUERY.gql, components/pages/submission-system/program-clinical-submission/index.tsx, components/pages/submission-system/program-clinical-submission/types.tsx
- adds a toast for dcc approval success
- refactors the `PageContent` component to use the `useClinicalSubmissionQuery` hook
- fixes the progress bar not showing (I derped earlier)
- fixes some content 
- updates clinical submission query on client side after dcc approves. (because the gql mutation does not return a `ClinicalSubmissionData`, cache must be updated manually)
=> Updates clinical submission approval

.env.schema
docker yells if there is white space in env vars before the '='
=> remove whitespace in env vars

components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx, components/pages/submission-system/program-clinical-submission/Header.tsx, components/pages/submission-system/program-clinical-submission/PageContent.tsx, components/pages/submission-system/program-clinical-submission/index.tsx, components/pages/submission-system/program-management/ManageProgramTabs.tsx, global/hooks/useUrlParamState.ts, tsconfig.json
- implements tab persistence in clinical submission with url
- creates a `useUrlParamState` to generalize persisting anything to url as string
- reimplements program management tab persistence with `useUrlParamState`
- `useUrlParamState` also fixes how the url wasn't being synced back to state in the program management page
=>  ✨ persists tab state in clinical submission page

components/pages/submission-system/ErrorNotification.tsx, components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx, global/utils/clinicalUtils.ts
Just making sure error tables also display rows with 1-index
=> 🐛 default error table row index should be 1-index

uikit/Icon/index.tsx
this should fix the escape css string escape problem for the icon component
=> 🐛 defaults svg.css to empty string

components/pages/submission-system/program-form/ProgramForm.tsx
The button wasn't being disabled because `isEqual()` doesn't do deep comparison so the changes in form arrays weren't being evaluated correctly. Changed to `isMatch()`
=> fix button stays enabled

uikit/Link/index.tsx
change format of css block so string interpolation doesn't contain illegal chars
fixes a lot of dev console warnings in external projects using uikit
emotion only throws the error when NODE_ENV != 'production' but it's a lot of effort to change this in some frameworks that have opinionated webpack commands that are hard to override eg. docusaurus
=> 🐛 refactor to remove illegal char

components/pages/submission-system/modals/editUser/index.tsx, global/hooks/useFormHook.tsx
On the EditUser modal, save button will remain disabled unless user form data is changed.
=> 🐛 1067 - prevent enabled save when user modal data is not changed

components/pages/submission-system/program-clinical-submission/PageContent.tsx
- Make clinical toast behave like registration toast
- Previously toast would get wiped away almost instantly ([see here ](https://drive.google.com/file/d/1R0Vi_Jl8KYbgOEaCdxJ88tmE60Lw_DhT/view?usp=sharing))
- Now it mimics the sample registration behaviour ([see here](https://drive.google.com/file/d/1gkrOOUQczC71vDPpv5xPd0IzhT-0XY4e/view?usp=sharing))
=> Make clinical toast behave like registration toast

Dockerfile
Updates Dockerfile to use non-root user
- uses the pre-configured `node` user provided by node base image, which has permissions set up to run `npm ci` (see doc: https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user)
=> 🐳 builds and runs container with non-root user

global/hooks/useProgramCheckEffect.tsx
- Whenever you would click on a program's page, while the program's existence was being checked, a loading modal was rendered
- In the case where the existence was confirmed to be true, the modal was wiped away so quickly that it looked like a strange flash on the page
- Added a 1200ms sleep before the modal removal so the loading animation is actually obvious before it gets wiped away
=> Add sleep() to loading modal to prevent flashes

components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
If uploading is disabled, the upload icon should be white.
=> Make upload icon white if disabled

components/pages/submission-system/ErrorNotification.tsx
Detailed error messages may have newline characters
Use set whitespace attr to `pre-line` so they show up
=> Make newlines in error messages show up as <br>

components/pages/submission-system/SideMenu.tsx
Adds key to submit clinical data sidebar to handle `INVALID_BY_MIGRATION` state
=> 🐛 Add invalid_by_migration key to clinical submission sidebar

components/pages/submission-system/program-dashboard/ProgramWorkspaceStatus/index.tsx, uikit/Link/index.tsx
When on the dashboard, collaborators should not see links to the `sample registration` and `clinical submission` page.
Made a wrapper function that returns the text only if the user is a collaborator, and the regular link otherwise.
PS: For whatever reason github, with this file, is showing some weird diffs that aren't there in my local branch. But whenever I pushed from my local, additional changes kept showing up. The only way I could figure out how to circumvent this was to manually add the changes with github's edit file tool, and not make the changes from my local setup.
=> Don't show links for collaborators

components/pages/submission-system/modals/editUser/index.tsx, components/pages/submission-system/modals/styledComponents.tsx, components/pages/submission-system/program-management/Users.tsx, components/pages/submission-system/program-management/UsersTable.tsx, uikit/form/Select/index.tsx, uikit/form/Select/stories.tsx
- A user cannot remove themselves from the manage users table
- A user cannot be removed if they are the last remaining admin
- the 1) **delete icon** and the 2) **edit user modal -> role dropdown** will be disabled if this is the case
- a tooltip on these components will show an explanation as to why
=> The last admin cannot be removed, a user cannot remove themselves

components/pages/submission-system/modals/addUser/index.tsx, components/pages/submission-system/modals/editUser/index.tsx, uikit/Modal/index.tsx
Adds margin to bottom of scrolling container instead of modal footer to give role dropdown room to display
Modal will scroll when enough users added
Added extra margin-bottom to Edit Users modal to prevent auto scroll, give dropdown room
=> 💄 1111 - Add margin bottom to scroll container to give role menu more space

.env.schema, components/pages/submission-system/common.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx, global/config.ts, next.config.js, uikit/Icon/icons/collection/dash.tsx, uikit/Icon/icons/index.tsx, uikit/Icon/index.tsx, uikit/Pipe/index.tsx, uikit/Pipe/stories.tsx, uikit/Table/styledComponent.tsx
- Built the donor summary table static state for the dashboard page ([zepplin ref](https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5deeac22f471a10775935a47)) .
- Defined the columns and the cell styles
- Defined the types for the table data
- Created 5 dummy records for demonstration purposes
- Dashboard render state is set by an environment variable
What was not done / other notes:
- sorting logic for some of the complicated cells (i.e samples, alignment)
- adding the filtering buttons and submenus
- integration with any data or states
- small scope change with the samples / raw reads column. Rendered both data into one cell rather than the colspan / merge cell like the ui mockup initially had
**Checklist before requesting …
=> Build Static State for Dashboard table

components/pages/submission-system/program-clinical-submission/PageContent.tsx
Under a program's clinical submission, if one of the files, (i.e. `donor.tsv`) had a priority status (i.e. `ERROR`), that tab would become the `selectedClinicalEntityType`.
When jumping straight to another program's clinical submission (on its first load), where a different file has priority status (i.e. `Specimen.tsv` is set to `WARNING`) the `selectedClinicalEntityType` tab would short circuit the logic and the intended tab with priority would not be highlighted.
Removed `selectedClinicalEntityType` in the condition.
=> Rely on default tab

components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
- Fixes how the updated cell is detected (this highlights the cell when pending approval)
+ basically just look at the `dataUpdates` and see if there's one with same `row` and same `fieldName`
- Fixes how the updated value is shown
+ same make sure to check for both same `row`
=> 🐛 fixes diff highlighting

components/pages/submission-system/SideMenu.tsx, components/pages/submission-system/program-clinical-submission/PageContent.tsx
- If the **first** file you try uploading in a clinical submission is an invalid one, it appears that the submission state remains as "null", ie. does not enter the `open` state
- In these cases, the side tab, then would not show an error state.
- Ensured that even in these null cases, error would show if they existed
=> 🐛Clinical Error state would not show in side tab

components/pages/submission-system/SchemaInvalidSubmissionNotification.tsx
Update the link to the dictionary that would show up in an `Invalid by Migration` error message, using the new links setup.
=> Fix link to dictionary within schema migration error

global/hooks/useAuthContext.tsx, global/utils/refreshJwt.ts, package-lock.json, package.json, pages/_app.tsx
Create queue for refresh requests to prevent more than one refresh happening at once.
Get jwt from cookies inside refresh function
=> 🐛 Create queue for refresh request to prevent parallel refreshes

components/pages/Homepage/common.tsx, components/pages/Homepage/index.tsx
- React grid systems calculation for row gutters are inconsistent, caused inconsistent renders of padding on the homepage
- Applied nogutter prop to the rows and defined the spacing manually instead
=> 🐛 Add noGutter prop to homepage rows

uikit/PercentBar/index.tsx
Percent bar set to 0% fill amount when denominator is `0`, prevent NaN result.
=> 🐛 Prevent NaN fill amount on percentBar

components/pages/file-repository/StatsCard/StatItem.tsx, components/pages/file-repository/StatsCard/index.tsx, components/pages/file-repository/index.tsx
- hides primary sites stat and chart for now.
- also moves the `Col` out of `StatItem` into `StatsCard/index` because it's easier to find where to change it when we add back later
=> :fire: hides primary sites stat and chart

components/pages/file-repository/FileTable/index.tsx
when filters change, table should reset to first page
=> 🐛 resets to page 0 when filters change

components/pages/file-repository/FacetPanel/index.tsx, components/pages/file-repository/FacetPanel/types.ts, components/pages/file-repository/FileTable/TsvDownloadButton.tsx, components/pages/file-repository/FileTable/index.tsx, components/pages/file-repository/FileTable/types.tsx, components/pages/file-repository/QueryBar/index.tsx, components/pages/file-repository/hooks/FILE_CENTRIC_EXTENDED_MAPPING.gql, components/pages/file-repository/hooks/useFileCentricFieldDisplayName.tsx, components/pages/file-repository/types.ts
pulls fields' display names from the gateway for:
- facet panel
- table
=> :sparkles: implements file repo field displaynames

components/pages/file-repository/FacetPanel/index.tsx
- keep facet aggregations in a state to render between filter change loads
- fade facet container and disable during loading 
- DNALoader didn't disable and cover entire facet container, can still see container when you scroll down on it
=> filerepo facets smoother transitions

components/pages/Homepage/index.tsx, global/hooks/useAuthContext.tsx, global/hooks/useProgramCheckEffect.tsx, pages/submission/program/[shortName]/dashboard.tsx
Set timeout to remove global loader on homepage when logging out, prevent sporadic endless loading state
=> 🐛 1357 - Set timeout for global loader on logout to home

global/hooks/useUrlParamState.ts
setting first render state without waiting for new url causing undefined in query paths
- move `setFirstRender` into onMount hook
- wait for router.replace to set first render state
=> unify onMount hooks, set first render after router replace

components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTableStatArea.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/InvalidDonorsNotification.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.gql, components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
- adds type for the `validWithCurrentDictionary` that comes with each donor summary record,
uses it to display an error icon in the table
- also uses it to manually count the total invalid donors, but expecting that to come as a statistic later ( like the other statistics )
=> Add error icons and notification banner to donor summary section

global/utils/pages/types.tsx, pages/index.tsx
used `getGqlQueriesToPrefetch` to cache the statistics for the homepage render
=> Server-side render of homepage stats

components/NavBar.tsx, components/pages/file-entity/index.tsx, components/pages/file-repository/FacetPanel/index.tsx, components/pages/file-repository/FileTable/index.tsx, components/pages/submission-system/SideMenu.tsx, components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx, components/pages/submission-system/program-clinical-submission/Header.tsx, components/pages/submission-system/program-dashboard/ProgramWorkspaceStatus/index.tsx, components/pages/submission-system/program-management/ManageProgramTabs.tsx, components/pages/submission-system/programs/index.tsx, global/hooks/useAuthContext.tsx
Auth Provider had both token state and a token prop.
This causes a conflict when a new token comes from `_app`
Removed this extra state.
@anncatton I believe you worked on this section last, so please take a look in case I've overlooked something.
In particular regarding refreshed JWTs vs initial.
I've tested it locally and it seems to work. Logging/logging out is always combined with routing to a new page so `_app` re-renders and passes down the most recent `egoJwt`
=> remove additional token state

components/pages/file-repository/FileTable/TsvDownloadButton.tsx, components/pages/file-repository/FileTable/index.tsx, components/pages/file-repository/StatsCard/StatItem.tsx, components/pages/file-repository/charts/SimpleBarChart/index.tsx, components/pages/submission-system/common.tsx, components/pages/submission-system/donor/ClinicalTimeline/index.tsx, components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx, components/pages/submission-system/program-clinical-submission/PageContent.tsx, components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTableStatArea.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/InvalidDonorsNotification.tsx, components/pages/submission-system/program-dashboard/DonorReleaseSummary/index.tsx, components/pages/submission-system/program-dashboard/StatsBar/index.tsx, components/pages/submission-system/program-management/ManageProgramTabs.tsx, components/pages/submission-system/program-management/Users.tsx, components/pages/submission-system/program-sample-registration/FileTable/index.tsx, components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx, components/pages/submission-system/program-sample-registration/index.tsx, components/pages/submission-system/programs/index.tsx, uikit/OptionsList/index.tsx, uikit/PercentageBar/index.tsx
- add commas to large numbers in text with `toLocaleString`
- aside from the requested changes, I looked for other instances of "pluralize" "count" and ".length"
- added screenshots to the ticket with everything i changed
=> 💄 add commas to large numbers

uikit/Tag/index.tsx
Adds a new purple background colour option to the Tag, as the component is being used for the new DACO app.
=> add tag colour for editable values

components/pages/file-repository/FacetPanel/FILE_REPOSITORY_FACETS_QUERY.gql, package.json
Release state is no longer available in the file-centric index mapping, meaning an error is thrown by arranger when this is requested by the UI. Since we are not using this piece of data, we should remove it from the api request. Hotfix to get these changes into staging and prod where we are observing this behaviour.
=> HOTFIX - Remove release_stage from facet query

uikit/Container/index.tsx, uikit/index.tsx
This selective props forwarding prevents the following error message, which comes up as a result of @emotion passing `loading` to the Container's div as an HTML attribute (which is a WIP for lazyloading of images https://github.com/whatwg/html/pull/3752).
=> fix "loading" being passed as html props to div error

components/pages/submission-system/donor/ClinicalTimeline/Timeline.tsx, uikit/Tag/index.tsx, uikit/VerticalTabs/index.tsx, uikit/VerticalTabs/stories.tsx
allows passing a new `disabled` props to the <VerticalTabs.item /> to disallow clicking on the tabs, and so people don't have to implement css customisation to reach the desired effect.
=> add disabled functionality for vertical tabs

uikit/Tooltip/index.tsx, uikit/VerticalTabs/index.tsx, uikit/VerticalTabs/stories.tsx
allows displaying a tooltip (optional) whenever you hover over a tab item, like so:
=> add optional tooltips to vertical tabs

uikit/form/FormCheckbox/index.tsx, uikit/form/FormCheckbox/stories.tsx
Restores functionality for individual `FormCheckbox`s (i.e. without needing a `RadioCheckboxGroup` context).
Bonus: migrates the component to TS, and adds Storybook actions.
Testable at https://fix-single-formcheckbox--argo-ui-storybook.netlify.app/?path=/story/uikit-form-formcheckbox--default
=> fix FormCheckbox not getting onChange without RadioGroup

uikit/form/FormControl/stories.tsx, uikit/form/FormHelperText/index.tsx
Allows making `FormHelperText` behave like an error message, hiding it when there's no errors to show.
Added it to `FormControl`'s story, to document visually the functionality: https://feature-formhelpertext-onerroronly--argo-ui-storybook.netlify.app/?path=/story/uikit-form-formcontrol--input
=> allow FormHelperText to behave as error message

uikit/form/FormCheckbox/index.tsx, uikit/form/FormCheckbox/stories.tsx, uikit/form/FormControl/FormControlContext.tsx, uikit/form/FormControl/index.tsx, uikit/form/FormControl/stories.tsx, uikit/form/common.tsx, uikit/theme/defaultTheme/radiocheckbox.tsx
Enables `FormControls` context and functionalities to be used in `FormCheckbox` components, including displaying the `required`  star and `error` statuses. 
Feature fully testable in this new `FormControl` story: https://feature-integrate-formcontrol-formcheckbox--argo-ui-storybook.netlify.app/?path=/story/uikit-form-formcontrol--formcheckbox
=> integrate FormCheckbox into FormControl

.env.schema, components/pages/submission-system/program-form/ProgramForm.tsx, uikit/form/Checkbox/index.tsx, uikit/form/FormCheckbox/index.tsx, uikit/form/FormCheckbox/stories.tsx, uikit/form/FormControl/FormControlContext.tsx, uikit/form/FormControl/index.tsx, uikit/form/common.tsx
Enables using the checkboxes' `blur` and `focus` events, and styles the `FormCheckbox` component accordingly, even when used inside a `FormControl`. 
Had to jump through a few hoops and loops because of the outdated version of React: `event.stopPropagation()` is basically useless in some scenarios. See this issue for more context. https://github.com/facebook/react/issues/4335#issuecomment-671487964
Can be tested here: https://feature-formcheckbox-focus-blur--argo-ui-storybook.netlify.app/?path=/story/uikit-form-formcheckbox--default
=> add checkbox focus and blur functionalities

uikit/Tag/index.tsx, uikit/package.release.json
Greys got mixed up. This restores them. Bumped UiKit version to prep for hotfix release.
=> restore repository facets grey tags tone

uikit/form/MultiSelect/index.tsx, uikit/form/Select/index.tsx, uikit/package.release.json
Dealing blur/focus behaviours at DACO, noticed there were some iffy behaviours in these two components when not using a mouse (tab + arrow keys).
As they are part of a same category, I've chosen to fix them together. No visible changes, and functionality should appear the same when using these at `platform-ui`.
PR Storybook: https://fix-selects--argo-ui-storybook.netlify.app/?path=/story/uikit-form-select--basic
=> improve event handling for Select and Multiselect

uikit/AppBar/DropdownMenu.tsx, uikit/AppBar/styledComponents.tsx, uikit/Button/index.tsx, uikit/Button/stories.tsx, uikit/ClipboardCopyField/index.tsx, uikit/Container/index.tsx, uikit/ContentPlaceholder/index.tsx, uikit/DropdownButton/index.tsx, uikit/FileSelectButton/index.tsx, uikit/Icon/InteractiveIcon/index.tsx, uikit/Icon/icons/collection/mail.tsx, uikit/Icon/icons/collection/trash.tsx, uikit/InstructionBox/index.tsx, uikit/Link/index.tsx, uikit/Modal/index.tsx, uikit/PercentageBar/index.tsx, uikit/Progress/index.tsx, uikit/SystemAlert/index.tsx, uikit/Table/SimpleTable/index.tsx, uikit/TitleBorder/index.tsx, uikit/Tooltip/index.tsx, uikit/VerticalTabs/index.tsx, uikit/VerticalTabs/stories.tsx, uikit/form/FormCheckbox/index.tsx, uikit/form/FormControl/index.tsx, uikit/notifications/Notification/index.tsx, uikit/notifications/Notification/styledComponents.tsx
It seems in an attempt to ensure the UiKits components were locked into a specific version of Emotion, the library doesn't respond correctly to their babel plugin settings.
This is creating styling issues when integrating the UiKit into another app, which may discourage its usage.
This PR ensures the components import the Emotion utilities directly from the package, rather than from a centralised import at the root of the library.
=> decouple emotion codependency

.env.schema, components/pages/file-repository/FacetPanel/FILE_REPOSITORY_FACETS_QUERY.gql, components/pages/file-repository/FacetPanel/index.tsx, components/pages/file-repository/FacetPanel/types.ts, components/pages/file-repository/types.ts, components/pages/file-repository/utils/constants.tsx, components/pages/file-repository/utils/index.ts
Adds FacetPanel aggregation facets for Embargo Stage (Access Tier) and Release State.
Release State will only show for DCC Admin users.
NOTE: Cannot be merged until the data sources in dev/qa have been updated with these fields.
=> Add EmbargoStage and ReleaseState facets

components/pages/file-entity/DataAndAnalysis/index.tsx, components/pages/file-entity/dummyData.tsx, components/pages/file-entity/types.tsx
File page was crashing for restricted files. The problem was attempting to render a table cell content from an object instead of string. The data structure of workflowType property was different (object instead of string) so by writing a snippet to convert this data into a presentable string everything loads and renders successfully.
=> Fix workflowType data structure to prevent file page crash

uikit/form/Select/index.tsx
When the Select component is implemented once in parallel state contexts, React seems unable to identify the parent container has changed the value passed into this component, creating a sticky internal state.
This easy commit simply adds an effect hook to ensure the state is updated if the value passed changes unexpectedly.
=> fix sticky values in Uikit Select

.storybook/PropTypesTable/ReactTableContainer.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.gql, components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx, components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx, package-lock.json, package.json, uikit/Button/index.tsx, uikit/DropdownPanel/index.tsx, uikit/DropdownPanel/stories.tsx, uikit/Icon/InteractiveIcon/index.tsx, uikit/Icon/icons/collection/filter.tsx, uikit/Icon/icons/index.tsx, uikit/Table/reactTableDefaultStyle.tsx, uikit/Table/styledComponent.tsx, uikit/Tooltip/index.tsx, uikit/Tooltip/stories.tsx, uikit/form/Input/index.tsx
Adds a new `DropdownPanel` component to UIKit which consists of:
- a trigger button (contents can be a UIKit icon, or anything you want by using the `customTrigger` prop)
- a fully accessible panel which opens/closes on button click, and additionally closes on click/focus outside the panel
- panel contents are passed as `children` to the `DropdownPanel` component
Storybook: https://feat-1983-donor-id-table-filter--argo-ui-storybook.netlify.app/?path=/story/uikit-dropdownpanel--basic
Also includes a [WIP] instance of the `DropdownPanel` being used as a filter in the column header for the Dashboard's Donor Summary Table to filter based on the `Donor ID` column
As well as some smaller changes to ensure the new component works:
- Add a new "filter" icon
- Extend …
=> ✨ Create Dashboard Filter Component (#1983)

uikit/Modal/index.tsx, uikit/Modal/stories.tsx
- allows passing of custom Footer element
- defaults to previous Footer with props for backwards compatibility
=> add custom Footer prop to Modal

.storybook/PropTypesTable/ReactTableContainer.tsx, uikit/DropdownPanel/index.tsx, uikit/Table/reactTableDefaultStyle.tsx, uikit/Table/styledComponent.tsx
Increase the `max-height` of the `DropdownPanel` component to prevent scroll bars from showing up when there are up to 4 items in the list (4 was chosen as it is the max number of options for the table header filters for the foreseeable future)
=> 🐛 Prevent Scrollbars on Dashboard Table Dropdown Filters (#2031)

components/pages/file-repository/FacetPanel/index.tsx, package.json
Ensure that the embargo stage facets are displayed in order of least->most permissive. Very minor fix, just changing which variable is being checked against to identify the correct facet to re-order.
=> Hotfix 1.101.3 - Embargo Stage Facet Ordering

uikit/form/MultiSelect/index.tsx, uikit/form/Select/styledComponents.tsx, uikit/form/Textarea/index.tsx, uikit/form/common.tsx, uikit/theme/defaultTheme/input.tsx, uikit/theme/defaultTheme/multiSelect.tsx, uikit/theme/defaultTheme/radiocheckbox.tsx
re: https://github.com/icgc-argo/dac-ui/issues/179
tested with storybook & setting fields on "create program" page to disabled
- make text inputs, checkboxes, radio buttons, select, and multiselect have grey text when disabled
- change textarea borders in disabled state
i refrained from reorganizing the colors, but i added a note in our uikit wiki page about organizing colors better.
=> update disabled colors in uikit

components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx, uikit/DropdownPanel/index.tsx
* Adds a 'Clear Filters' button to the dashboard table to facilitate clearing any/all filters at once
=> ✨ Add 'Clear Filters' Button to Dashboard Table Header (#2035)

uikit/form/MultiSelect/index.tsx
remove the change event and `name` attribute (which would cause a change event to fire on autocomplete)
those changes had no effect on platform, and the wrong effect on DACO, so rolling back for now.
previous PR: https://github.com/icgc-argo/platform-ui/pull/2053/
=> revert changes from uikit 1.14.1

components/pages/file-repository/StatsCard/STATS_BAR.gql, components/pages/file-repository/StatsCard/index.tsx
Paying rent for staying at @joneubank 
Change the stats aggregation to use `bucket_count` rather than counting buckets to reduce amount of data transported. 
Tested to confirm working.
=> ⚡️ use bucket_count aggregation instead of counting buckets

components/pages/user/ApiTokenBox/index.tsx, components/pages/user/index.tsx, pages/user/index.tsx
Disables use of Generate API Token button for users w/o DACO Access or Program Membership
Updates copy for above scenario
Updates 'Expired' tag logic to only render when user's api token is expired, not in other scenarios
=> 🐛  #1794 Handle Users with no Access

uikit/Table/SimpleTable/index.tsx
Adds word-break property to Simple Table component to break up lengthy donor IDs and other values
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2197
=> 🐛 #2197 Wrap long Donor ID values

components/pages/file-entity/FILE_ENTITY_QUERY.gql, components/pages/file-entity/FileCardsLayout.tsx, components/pages/file-entity/SequencingReadProperties/index.tsx, components/pages/file-entity/dummyData.tsx, components/pages/file-entity/index.stories.tsx, components/pages/file-entity/types.tsx, components/pages/file-entity/useEntityData.tsx
* Adds `metrics` object to the `FILE_ENTITY_QUERY.gql`
* Renders the `Sequencing Reads Properties` section of the File Entity page for `Aligned Reads` files
* Adds a type for the `metrics` data
=> 🚩 Enable `Sequencing Reads Properties` Section of File Entity Page (#2219)

components/pages/file-entity/FileCardsLayout.tsx, components/pages/file-entity/SequencingReadProperties/index.tsx, components/pages/file-entity/types.tsx, components/pages/file-entity/useEntityData.tsx
* Fixes a crash that would occur when the received `metrics` object would not match the schema
* Adds `null` checks, makes the object generation more generic for future expandability
=> 🐛 Make `metrics` handling more generic, and add checks for `null`

components/pages/file-entity/useEntityData.tsx
* Use lodash `isObject` to check type instead of relying on `typeof`, preventing a crash where the UI would try to do an `Object.values()` call on a null metrics object
=> 🐛 Fix crash when `metrics` is `null`

components/pages/file-repository/FileTable/TsvDownloadButton.tsx
Fixes bug where clicking on 'Number of selected files' shows loading spinner
Aligns with behaviour used in HCMI & DCC for the same button (menu closes when clicking 'number of files')
=> 🐛 #2241 Prevent Loading on Selected File # Click

components/pages/file-repository/FileTable/index.tsx
Adds blue 'descending' header band by default to File ID column on table
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-api/521
See comments in ticket
=> 💄 #521 Default Blue Descending Header Band

components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
Original Appearance of Clinical Submitted Page Table (There are two types of table on this page. This type has two titles)
Scroll to the Right of Table and `donor_id` Column Will Follow
Width Change of `donor_id` Column Won't Cover Up Nor Affect the Alignment of the Rest of the Table
Change the Width of `donor_id` Column and Scroll to the Right
The Same Function Works on the Second Type of Table (Table with one title)
=> #2374 Feature Request - Make Donor Id Column visible All the Time

components/Head.tsx
favicon which is the icon in the browser tab is missing. The directory of use to obtain the image file is updated and issue solved.
works in Chrome tab
works in Firefox tab
=> Style/2458 QA favicon missing

Jenkinsfile.groovy
- add `--no-verify` when Jenkins makes commits for QA builds
- this is to fix the issue where Jenkins can't find NPM
- this is **temporary fix** so we can do a QA release this week.
=> #2483: add no verify to QA git push

components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
- round up Y axis labels to be multiples of the number of horizontal guides
- tweak positioning of Y axis coordinates
=> #2457: molecular chart display bug

components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
Add optional chaining so donors without this alert don't break the table when the page size is changed.
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2456
=> #2456: fix pagination in Donor Summary Table

components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
- when the highest Y value is 4 or more digits, it pushes the chart lines down
- add an adjustment to push the lines back up
- tested with 2 - 6 digit max Y values
=> #2457: bug: fix Y axis positioning

components/pages/file-entity/DataAndAnalysis/index.tsx, global/constants/index.tsx
Update names and links of `Genome Build`, `Genome Annotation`, `Workflow Version` for a new Workflow Type, "RNA Seq Alignment". 
When Workflow Name is "RNA Seq Alignment", `Genome Build`, `Genome Annotation` and `Workflow Version` is updated to values specific to this Workflow Name:
Link to Genome Build, "GRCh38_Verily_v1" (open in a new tab)
File downloaded with Genome Annotation link, "GENCODE v40" 
Link to Workflow Version, dynamic to tag number. In this case, 0.1.1
=> Issue#2240: File Entity page: doc links update for new RNA workflows

components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTableLegend.tsx, generated/gql_types.tsx
- issue 1: couldn't reproduce. I think it's fixed in another PR
- issue 2: add double exclamation point operator to error display check, because it was showing a 0
=> roadmap #927: fix error display when there's no errors

components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
At the bottom of `Filter Modal`, Unmatched IDs count is incorrect due to double counting the same entry when both its donor_id and submitter_id are entered in the text box. A function, `numOfDoubleCountedId()` is created to count the instance and then subtracted from the `initialIdsCount`.
The following screenshots are in program, HNAHAL. The inputs are two donor_ids and submitter_id pairs. 
Without removal of double counting, in DEV, instead of Matched IDs = 2, there is also Unmatched IDs = 2. The unmatched IDs are incorrect.
With the new function that removes the double count, the Unmatched IDs is now 0. This screenshot is in localhost, …
=> #2549 Filter By Submitter Donor id And Donor id for same Donor Gives Confusing Results

components/pages/submission-system/program-submitted-data/SearchBar/index.tsx, components/pages/submission-system/program-submitted-data/SearchBar/style.tsx
Fixes margin between 'Clinical Data' download button on Submitted Data Search Bar on small browser windows
**In Dev/QA:**
See Clinical Data Download Button
**This branch:**
=> 🧽 Chore: Fix Submitted Data Search Bar Margin

components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
UI was incorrectly rendering all Normal/Tumour Specimen stats
Should only render stats for records with submitted Clinical Info
=> 🐛 Revise Normal/Tumour Stats after updating Specimen Stats on Clinical

components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx, components/pages/submission-system/program-submitted-data/common.tsx
Leverages React Table tdProps to pass Specimen Completion error data when calculating styles
Outcome from QA testing of:
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2580
=> 🕷️ Updated NS/TS Display Logic

components/pages/submission-system/SideMenu.tsx, components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx, components/pages/submission-system/program-submitted-data/common.tsx, components/pages/submission-system/program-submitted-data/index.tsx, package-lock.json
Changes related to Clinical #1006: https://github.com/icgc-argo/argo-clinical/pull/1051
Adds default values for empty clinicalErrors response
=> #1006 🐛 Null clinical error fix

components/pages/submission-system/program-dashboard/DonorDataSummary/DownloadButtons.tsx, components/pages/submission-system/program-submitted-data/DownloadButtons.tsx
Update URL path for all calls to clinical proxies. The path is being updated form `/clinical/programs` to `/clinical/proxy/programs` in the platform-api: https://github.com/icgc-argo/platform-api/pull/673
Two buttons interact with download requests through this proxy, both have been updated.
=> Update proxy paths to match API update

components/pages/file-repository/FileTable/TsvDownloadButton.tsx
Removes the Clinical Data download option on the file repo from users unless they are DACO approved.
=> Clinical Data download only shows for DACO Approved Users

components/pages/program-entity/ProgramCardsLayout/util.tsx, components/pages/program-entity/gql/PROGRAM_SUMMARY_QUERY.ts, components/pages/program-entity/types.tsx, components/pages/submission-system/create-program/index.tsx, components/pages/submission-system/gql/PROGRAM_VALUES_QUERY.ts, components/pages/submission-system/program-form/ProgramForm.tsx, components/pages/submission-system/program-form/validations.tsx, components/pages/submission-system/program-management/ManageProgramTabs.tsx, components/pages/submission-system/program-management/Profile.tsx, components/pages/submission-system/program-management/gql/PROGRAM_QUERY.ts, generated/gql_types.tsx, global/utils/common.tsx
Removes all references to Region field for programs
- Create Program is not working yet, requires dataCenters added to Query
- Update program showed a success message, but on 2nd login data was unchanged, so this likely requires Program Service updates
Adds handling for Date formatting which is breaking on localhost
https://github.com/icgc-argo/platform-ui/issues/2724
https://github.com/icgc-argo/platform-api/pull/716
=> 🗺️ #2724 Remove Regions

components/pages/program-entity/ProgramCardsLayout/util.tsx, components/pages/program-entity/gql/PROGRAM_SUMMARY_QUERY.ts, components/pages/program-entity/types.tsx, components/pages/submission-system/create-program/index.tsx, components/pages/submission-system/gql/PROGRAM_VALUES_QUERY.ts, components/pages/submission-system/program-form/ProgramForm.tsx, components/pages/submission-system/program-form/validations.tsx, components/pages/submission-system/program-management/ManageProgramTabs.tsx, components/pages/submission-system/program-management/gql/PROGRAM_QUERY.ts, components/pages/submission-system/programs/gql/PROGRAMS_LIST_QUERY.ts, generated/gql_types.tsx
Adds DataCenter fields to UI pages & Queries (especially Create / Update Program)
Related API Changes: https://github.com/icgc-argo/platform-api/pull/717
Screenshots: https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/roadmap/1098
=> ⌨️ #1098 Add Data Center fields

components/pages/file-repository/FileTable/index.tsx
This change restores the original behaviour for the select all button on the file repo, which is that the allRowsSelected variable is true but we don't list any selected rows. The implementation being removed here is incorrectly setting the selected rows to include only the current page of results, despite the "select all" graphics indicating the entire set is selected.
A long term solution to downloading a larger clinical data set is still required, this is simply removing a UI change that would possibly introduce confusing behaviour.
=> Select all on file repo does not select files for clinical download

components/pages/file-repository/FileTable/TsvDownloadButton.tsx
reference ticket url: https://github.com/icgc-argo/roadmap/issues/1056#event-15640319491
In this PR, I've addressed an issue with the clinical download functionality when using the "Select All" feature in the table and requesting clinical download files. Previously, the clinical download button remained active even when all rows were selected. This would lead to an non descriptive error response from the server due to processing files.  
Now, the button is automatically disabled whenever the "Select All" function is triggered. This change addresses part one of the ticket work "Quick/Temporary Solution". Implementing code to identify when "Select All" is selected and disabling "Clinical Data" download from the dropdown by conditionally rendering it. As we do not even render the button, …
=> disabled clinical download button when all files are selected
