- client/uikit/Icon/icons/collection/slash.js
- client/uikit/Icon/icons/index.js
- client/uikit/TitleBar/index.js
- client/uikit/TitleBar/index.test.js
- client/uikit/TitleBar/stories.js
- client/uikit/theme/defaultTheme/index.js
- client/uikit/theme/defaultTheme/titleBar.js
> Add title bar

- .github/ISSUE_TEMPLATE/data-hookup-template.md
Created an issue template for "Data Hookup" types of issues
> Update issue templates

- Jenkinsfile.gateway.groovy
- Jenkinsfile.ui.groovy
> add step to deploy

- client/uikit/PercentageBar/index.js
Addresses feedback in issues https://github.com/icgc-argo/argo-platform/issues/74
> updates layout of the PercentageBar

- client/uikit/Table/TablePagination/index.js
- client/uikit/Table/TablePagination/stories.js
- client/uikit/form/Select/index.js
> Fix styles issues for TablePagination

- client/components/pages/submissionSystem/programs/ProgramsTable.js
- client/components/pages/submissionSystem/programs/queries.gql
Handles null fields coming from programs query
#ILoveStaticTypes
> 🐛 handles null fields in programs query response

- server/app.js
- server/config.js
tracing is good for query performance analysis
> Enables Apollo tracing

- client/uikit/Footer/index.js
- client/uikit/Footer/stories.js
- client/uikit/PageLayout/index.js
> Adjust footer styles 

- client/uikit/Footer/index.js
- client/uikit/PageLayout/index.js
> Fix table width and footer height

- client/components/pages/submissionSystem/programs/index.js
- client/e2e/helpers.js
- client/e2e/scripts/local.runner.js
- client/e2e/tests/login/login.js
- client/e2e/tests/programs/programs.js
This just adds the test for the programs page. 
Next step: figure out the CI integration of this e2e test.
> adds some tests for the programs page

- client/uikit/Button/GoogleLogin/index.js
We want to login with Google, not login with the Google
> remove "the" in button

- client/uikit/Icon/index.js
- client/uikit/Modal/index.js
- client/uikit/Modal/stories.js
just making the existing modal component configurable to match the small version.
> Modal UI small version

- client/pages/401.js
- client/pages/404.js
- client/pages/500.js
We don't actually need these pages so removing them to lower build overhead
> removes error pages to speed up build

- server/schemas/Program/index.js
- server/services/programService/index.js
> Update User and Remove User gateway connections

- client/components/pages/submission-system/layout.js
- client/uikit/Modal/index.js
- modal fades in
- uses `position: fixed` to support smaller screens (`position: absolute` doesn't work well on longer pages / short screens)
> fancy little modal fade

- client/components/pages/submission-system/programs/ProgramsTable.js
display shortName before programName
- [ x ] Styling
> display shortName before programName

- client/.env.schema
- client/global/config.js
- client/next.config.js
- client/pages/_app.js
Just for dev, allow config to bypass auth.
> Adds env var to bypass auth to support remote dev

- client/uikit/form/Input/index.js
Cosmetic change to something bothering me - Area around text inputs was showing a "finger" (pointer) style cursor, now it will be a text cursor.
Also added an on-click event to this area around the text entry box to add focus to the form element on click
> Change cursor around text input to text cursor

- .github/pull_request_template.md
Fix minor typos in PR template
> :pencil2: Fix minor typos in PR Template

- client/components/pages/submission-system/program-management/index.js
- client/uikit/TitleBar/index.js
remove left padding in TitleBar
remove 'Program Name' in title bar
> remove padding on title bar

- client/components/pages/submission-system/NavBar.js
Please add a brief description of the changes here.
> capitalizes user role in NavBar

- client/components/pages/submission-system/modals/deleteUser/index.js
- client/components/pages/submission-system/modals/deleteUser/index.stories.js
- client/components/pages/submission-system/program-management/Users.js
> add delete user modal

- client/uikit/form/Input/index.js
> implements input focus using ref

- client/components/pages/submission-system/create-program/CreateProgramForm.js
- client/components/pages/submission-system/program-management/Profile.js
- client/components/pages/submission-system/programs/ProgramsTable.js
- server/package-lock.json
- server/package.json
- server/schemas/Program/index.js
- server/services/ego/index.js
- server/services/programService/index.js
- server/utils/grpcUtils.js
* Set the Program service proto dependency to the latest version(0.0.3)
* Update the gateway to match the changed shape
* Program uses Arrays for countries, regions, institutions
* ProgramUsers include invitation details
* User's list is nullable, this is important for the case where the getUsers separate request fails
* Update the client to match the changed Program shape
* Create/Update program form
* Program Management page
* All Programs table
> Feat/upgrade ps 0.0.3

- server/services/programService/index.js
Update the format of countries, regions, institutions passed to UpdateService rpc in ProgramService GRPC.
> :bug: Fix message structure for update program to grpc

- server/services/programService/index.js
> :bug: Fix message structure for update program to grpc (#344)

- client/uikit/AppBar/index.js
- client/uikit/utils/useClickAway/index.js
- client/uikit/utils/useClickAway/stories.js
Abstract the click away logic to a reusable hook.
> 🎨 abstract clickaway logic to a reusable hook

- Jenkinsfile.gateway.groovy
- Jenkinsfile.ui.groovy
Updating Jenkins credential for CI
> updates jenkins dockerhub credentials

- client/components/pages/submission-system/program-management/UsersTable.js
> title fixes

- client/components/pages/submission-system/SideMenu.js
Implements selected items in the left navigation bar based on current page path
> implements selected state for menu items based on path

- client/components/pages/submission-system/program-clinical-submission/index.js
- client/components/pages/submission-system/program-dashboard/index.js
- client/components/pages/submission-system/program-id-registration/index.js
- client/components/pages/submission-system/program-management/index.js
Add actual program short name to the page title
> add program short name to page titles

- client/global/utils/egoJwt/index.js
- client/package-lock.json
- client/package.json
> updates ego token util

- client/components/pages/submission-system/program-clinical-submission/index.js
- client/components/pages/submission-system/program-dashboard/index.js
- client/components/pages/submission-system/program-id-registration/index.js
- client/components/pages/submission-system/program-management/index.js
- client/global/utils/egoJwt/index.js
- client/package-lock.json
- client/package.json
* add program short name to page titles
* use page context instead of router
Please add a brief description of the changes here.
> deploys latest

- Jenkinsfile.gateway.groovy
- Jenkinsfile.ui.groovy
> adds jenkins slack integration

- client/components/pages/submission-system/layout.js
- client/components/pages/submission-system/program-management/Users.js
- client/components/pages/submission-system/toaster.js
- client/uikit/notifications/Toast/index.js
- client/uikit/notifications/Toast/stories.js
Sets up a global toaster system at submission section layout root. This is sufficient for now but we may need to refactor to lift this up at some point.
> implements basic toaster

- client/components/pages/submission-system/program-management/Users.js
- client/components/pages/submission-system/toaster.js
- Hooks up ability to add toast with custom interactionType, I forgot this in earlier PR.
- Also better flow type
> hooks up ability to add toast with custom interactionType

- client/components/pages/submission-system/SIDE_MENU_PROGRAM_LIST.gql
- client/components/pages/submission-system/SideMenu.js
- client/components/pages/submission-system/program-management/Users.js
- client/components/pages/submission-system/toaster.js
- client/pages/submission/program/[shortName]/clinical-submission.js
- client/pages/submission/program/[shortName]/dashboard.js
- client/pages/submission/program/[shortName]/id-registration.js
- client/pages/submission/program/[shortName]/manage.js
- client/pages/submission/program/index.js
Not urgent, just having it on standby for next time we want to deploy
> deploy latest

- client/components/pages/submission-system/program-management/Users.js
Literally serves no purpose but fixing Minh's OCD
> fixing Minhs OCD

- client/components/pages/submission-system/create-program/CreateProgramForm.js
add required to Institution field
> add required to Institution field

- client/uikit/PageLayout/index.js
- client/uikit/TitleBar/index.js
> reduce padding on titlebar

- client/components/pages/submission-system/modals/addUser/index.js
- client/components/pages/submission-system/modals/common.js
- client/components/pages/submission-system/modals/deleteUser/index.js
- client/components/pages/submission-system/modals/editUser/index.js
- client/components/pages/submission-system/modals/resendInvite/index.js
- client/components/pages/submission-system/modals/resendInvite/index.stories.js
- client/components/pages/submission-system/modals/styledComponents.js
- client/components/pages/submission-system/modals/validations.js
- client/components/pages/submission-system/program-management/EDIT_USER_MUTATION.gql
- client/components/pages/submission-system/program-management/INVITE_USER_MUTATION.gql
- client/components/pages/submission-system/program-management/ManageProgramTabs.js
- client/components/pages/submission-system/program-management/PROGRAM_QUERY.gql
- client/components/pages/submission-system/program-management/Users.js
- client/components/pages/submission-system/program-management/UsersTable.js
- client/components/pages/submission-system/program-management/index.js
- client/global/constants/index.js
- client/uikit/Table/InteractiveIcon.js
- server/schemas/Program/index.js
> 🚀 Deploy! 

- client/components/ApplicationRoot.js
- client/components/pages/NavBar.js
- client/components/pages/submission-system/SideMenu.js
- client/components/pages/submission-system/program-clinical-submission/index.js
- client/components/pages/submission-system/program-dashboard/index.js
- client/components/pages/submission-system/program-id-registration/index.js
- client/components/pages/submission-system/program-management/ManageProgramTabs.js
- client/components/pages/submission-system/program-management/UsersTable.js
- client/components/pages/submission-system/program-management/index.js
- client/components/pages/submission-system/programs/index.js
- client/components/pages/submission-system/register/index.js
- client/global/hooks/useAuthContext.js
- client/global/utils/egoJwt/index.js
- client/global/utils/getApolloCacheForQueries.js
- client/global/utils/pages/types.js
- client/pages/_app.js
- client/pages/logged-in.js
- client/pages/user/index.js
Implements the auth context as actual context with initial value set from server-side. This avoids the null initial state that only gets flipped when JS is executed in client, resulting in the flash. Also this fixes https://github.com/icgc-argo/argo-platform/issues/404 which was caused by the local component's auth state not properly flipping.
> Implements auth context as global context

- client/components/ApplicationRoot.js
- client/components/pages/submission-system/layout.js
- client/components/pages/submission-system/program-management/ManageProgramTabs.js
- client/components/pages/submission-system/program-management/Users.js
Makes modal portal available globally
> moves modal portal to ApplicationRoot

- client/.flowconfig
- client/uikit/form/Checkbox/index.js
- client/uikit/form/Checkbox/stories.js
- client/uikit/form/FormCheckbox/index.js
- client/uikit/form/FormCheckbox/stories.js
- client/uikit/form/Radio/index.js
- client/uikit/form/Radio/stories.js
added missing aria roles
for some reason storybook still complains about no aria-checked on Radio. but it's wrong.
> added some aria attributes

- client/uikit/PageLayout/index.js
> fix ocd inducing gap

- client/uikit/PageLayout/index.js
With the fix of the OCD-inducing gap
> 🚀 Deploys latest

- client/components/pages/submission-system/programs/PROGRAMS_LIST_QUERY.gql
- client/components/pages/submission-system/programs/index.js
- client/pages/submission/program/index.js
prefetches the table data on server side
> ⚡️ prefetch programs list page data

- server/package-lock.json
- server/schemas/Program/index.js
- server/services/programService/index.js
Fixes UpdateUser schema and service to match v0.0.4 ProgramService Proto: Use userEmail instead of userId for update.
> UpdateUser uses email not id

- client/components/pages/user/ProgramAccessBox.js
just the static daco approval status display
> adds the daco approval status display

- client/components/pages/submission-system/create-program/index.js
- client/uikit/Container/index.js
- redirects user to `/submission/program` after program creation
- disable form while redirect is happening
> program create redirect

- client/components/pages/submission-system/ProgramForm.js
- client/components/pages/submission-system/create-program/validation.js
- client/components/pages/submission-system/programs/index.js
- client/components/pages/submission-system/register/joinProgramForm/index.js
- client/uikit/form/Checkbox/index.js
- client/uikit/form/Checkbox/stories.js
- client/uikit/form/MultiSelect/index.js
- client/uikit/form/RadioCheckboxGroup/index.js
- client/uikit/form/Select/index.js
- client/uikit/form/Select/styledComponents.js
Added data-values to many of the uikit form elements
Added IDs to several unique buttons
> Minor Details to help with Automated E2E Testing

- client/uikit/ThemeProvider/index.js
- client/uikit/index.js
- client/uikit/theme/defaultTheme/appBar.js
- client/uikit/theme/defaultTheme/button.js
- client/uikit/theme/defaultTheme/colors.js
- client/uikit/theme/defaultTheme/index.js
- client/uikit/theme/defaultTheme/input.js
- client/uikit/theme/defaultTheme/multiSelect.js
- client/uikit/theme/defaultTheme/radiocheckbox.js
- client/uikit/theme/defaultTheme/shadows.js
- client/uikit/theme/defaultTheme/titleBar.js
- client/uikit/theme/defaultTheme/typography.js
`useTheme` now comes with flow type
> adds flow to theme

- .github/pull_request_template.md
Updates this template to have `Please add a brief description of the changes here.` as comment
> makes 'Please add a brief description of the changes here.' a comment

- Jenkinsfile.gateway.groovy
- Jenkinsfile.ui.groovy
Adds Jenkins step to deploy to dev on merge to `develop` branch
> adds CD to dev environment

- client/components/NavBar.js
> dummy commit

- client/components/pages/submission-system/modals/addUser/index.js
Corrects issue adding new users introduced in form hook refactor
> Fix Add User form handling

- Jenkinsfile.gateway.groovy
Updates Gateway Jenkinsfile update to work with multi-branch pipeline
> Gateway Jenkinsfile update

- Jenkinsfile.groovy
- components/pages/submission-system/SideMenu.js
- components/pages/submission-system/program-sample-registration/index.js
- global/constants/pages.js
- global/utils/pages/index.js
- pages/submission/program/[shortName]/sample-registration.js
- Changes "id registration" to "sample registration"
- Updates CI to run flow check during test
> changes id registration to sample registration

- components/pages/submission-system/ProgramForm.js
> check against form seed data to enable save

- components/pages/submission-system/modals/common.js
- global/constants/index.js
Removes Curator as an option from UI.
Changes display name of `Submitter` to `Data Submitter`
> Removing Curator, changing submitter display

- components/submission-system/register/joinProgramForm/JOIN_PROGRAM.gql
removes unused gql file
just a treeshake
> 🔥 removes unused file

- components/ApplicationRoot.js
- fixes bug found by @d8660091 of page refresh when toasting
> 🐛 refactor the ApplicationRoot to prevent re-render when toast

- components/pages/submission-system/join/GET_INVITE.gql
- components/pages/submission-system/join/index.js
- Redirect user to the program dashboard when successfully joined a program
- Show a toast when user failed to join a program
> Handling feedbacks from server

- components/pages/submission-system/program-management/ManageProgramTabs.js
just a small refactoring for aesthetic
> ♻️ removes inlined onSubmit on AddUserModal

- components/pages/submission-system/ProgramForm.js
- components/pages/submission-system/create-program/index.js
- components/pages/submission-system/program-management/ManageProgramTabs.js
- global/hooks/useFormHook.js
- updates url when user navigates the programs management tabs
- reimplements form reset with a built-in solution to `useFormHook`
> update url when user navigates program management tabs

- components/pages/user/ProgramAccessBox/index.js
- Removes the data fetching for DCC and just show `"All Programs"`
- Make the short names in programs table a link to the program dashboard. Program list page for dcc
> Updates user profile page

- pages/_app.js
- Remove cookie and redirect now don't rely on express
- Redirect now works in both front end and backend
t
> Fix remove cookie and redirect functionality

- components/pages/submission-system/layout.js
- components/pages/submission-system/program-sample-registration/FileTable/index.js
- components/pages/submission-system/program-sample-registration/index.js
- uikit/InstructionBox/index.js
- uikit/Progress/index.js
- uikit/Typography/index.js
- uikit/notifications/Banner/index.js
- uikit/notifications/Banner/stories.js
- uikit/notifications/Notification/index.js
- uikit/notifications/Notification/stories.js
- adds static layout for sample registration page
- adds some flow types for `uikit/Typography` and `uikit/notifications/Banner`
> sample registration page layout

- components/pages/user/ProgramAccessBox/index.js
- adds text to inform no access for public user
> ✨ adds message to inform user of no access

- components/pages/submission-system/programs/PROGRAMS_LIST_QUERY.gql
- components/pages/submission-system/programs/ProgramsTable.js
- components/pages/submission-system/programs/index.js
> Add data to administrators column

- components/pages/user/ProgramAccessBox/index.js
- package-lock.json
> hide empty data table when user has no programs

- components/pages/submission-system/programs/index.js
> Make title h1

- global/utils/form/error.js
- global/utils/form/validations.js
> add email validation

- uikit/Table/TablePagination/index.js
- uikit/form/Select/index.js
- uikit/form/Select/styledComponents.js
> Move row selections up

- uikit/PageLayout/index.js
> Fix left sidebar

- components/pages/DefaultLayout.js
- uikit/utils/useClickAway/index.js
> Use standard API to detect if element is a child

- uikit/theme/defaultTheme/typography.js
> change font sizes

- components/pages/submission-system/layout.js
- components/pages/user/index.js
- uikit/PageLayout/index.js
> Fix width issue at user profile page

- components/NavBar.js
- uikit/AppBar/DropdownMenu.js
The profle & token link does not respond to the user click on the blank
area
> Fix profile & token link

- components/pages/submission-system/programs/ProgramsTable.js
- components/pages/submission-system/programs/index.js
- pages/submission/program/index.js
Program list is slow to fetch. Instead of doing it on server end, I make
the change to do it on client side. So the user can be redirected
immediately.
> Lazy load program list

- components/pages/user/index.js
- pages/maintenance.js
> Change typography to h1

- components/ApplicationRoot.js
- components/Head.js
> Add favicon

- components/pages/submission-system/create-program/CREATE_PROGRAM_MUTATION.gql
Updates to match change made in gateway, prevents CreateProgram failure toast depsite successful creation.
> Update CreateProgram query to expect no return data

- pages/maintenance.js
> Change semantic of typography

- components/pages/submission-system/ProgramForm.js
- components/pages/submission-system/QUERY_PROGRAM_VALUES.gql
- components/pages/submission-system/create-program/index.js
- components/pages/submission-system/create-program/validation.js
- components/pages/submission-system/join/GET_JOIN_PROGRAM_INFO.gql
- components/pages/submission-system/join/JOIN_PROGRAM.gql
- components/pages/submission-system/join/JOIN_PROGRAM_MUTATION.gql
- components/pages/submission-system/join/index.js
- components/pages/submission-system/join/joinProgramForm/index.js
- components/pages/submission-system/join/joinProgramForm/index.stories.js
Fetch program options from gateway for create/edit program form, and institutions for join program form
> Program Form uses lists from Program Service

- components/ApplicationRoot.js
- components/pages/submission-system/ProgramForm.js
- components/pages/submission-system/SideMenu.js
- components/pages/submission-system/create-program/index.js
- components/pages/submission-system/join/index.js
- components/pages/submission-system/program-management/ManageProgramTabs.js
- components/pages/submission-system/program-management/Users.js
- components/pages/submission-system/program-management/index.js
- components/pages/submission-system/programs/index.js
- components/pages/user/AccessKeyBox/index.js
- global/contexts/ApolloHooksProvider.js
- package-lock.json
- package.json
Bump `react-apollo` version
Use official `@apollo/hooks` package
> add official apollo hooks lib

- components/pages/submission-system/join/index.js
- global/hooks/useAuthContext.js
- package-lock.json
Previously the error was caught in the copy/pasted promise code, and not rethrown causing it to miss the error handling of the toaster in the calling context. For some reason this resulted in a crash/lockup of the UI. See here: #599
> 🐛 Better promise handling in updateToken

- components/pages/submission-system/SideMenu.js
- components/pages/submission-system/program-sample-registration/Instructions/index.js
- components/pages/submission-system/programs/PROGRAMS_LIST_QUERY.gql
- components/pages/submission-system/programs/PROGRAMS_USERS_QUERY.gql
- components/pages/submission-system/programs/ProgramsTable.js
- components/pages/submission-system/programs/index.js
- pages/submission/program/[shortName]/clinical-submission.js
- Loading programs table in two steps. First load the basic info, then
load the admins
- Fix dynamic route Link. All navigation should happen instantly
- Fix `<a>` inside `<a>`
> Fix a bunch of performance issues

- components/pages/submission-system/program-sample-registration/Instructions/index.js
> Add file download link

- components/pages/user/AccessKeyBox/index.js
- uikit/ClipboardCopyField/index.js
> access key box updates

- uikit/Tooltip/index.js
Cleaning up my mess, I totally derped on previous PR
> 🐛 fixes wrong emotion Global usage

- components/pages/submission-system/program-sample-registration/FileTable/index.js
- components/pages/submission-system/program-sample-registration/index.js
fix type checking
reverted table logic back to original
> fix type for FileTable sample registration

- uikit/TitleBar/index.tsx
> Use titlte typography

- components/pages/error.tsx
> Use global footer in error page

- components/pages/submission-system/program-sample-registration/FileTable/NoDataMessage.tsx
- components/pages/submission-system/program-sample-registration/FileTable/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- uikit/Table/NoDataComponent.tsx
- uikit/Table/index.tsx
> Do not render nodata component when loading

- components/pages/submission-system/modals/addUser/index.tsx
- components/pages/submission-system/modals/styledComponents.tsx
> Disable disable and remove padding-bottom

- components/Footer.tsx
- global/constants/index.tsx
- displays UI version from package.json in footer
> ✨ adds ui version from package.json to footer

- components/pages/submission-system/program-management/ManageProgramTabs.tsx
- components/useCommonToasters.tsx
**Description**
Handle success saving feedback
> Handle success saving feedback

- uikit/form/MultiSelect/index.tsx
> Fix a multiselect AllowNew bug that causes new value be created

- components/pages/submission-system/program-management/ManageProgramTabs.tsx
- components/pages/submission-system/program-management/Users.tsx
- components/pages/submission-system/program-management/UsersTable.tsx
> Remove pagination and add loading state for user table

- uikit/form/MultiSelect/Option.tsx
Display multiple lines for multiselect option
> Display multiple lines for multiselect option

- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
always say the DCC
add punctuation and grammar 
- spelling has been FIXED as it was incorrect.
> fix typos in registration pages

- components/pages/submission-system/program-sample-registration/index.tsx
remove unusued line throwing err
> remove unusued line throwing err

- uikit/Tag/index.tsx
- uikit/VerticalTabs/index.tsx
- uikit/VerticalTabs/stories.tsx
creates new ui component to be used in Clinical Submission page
> ✨ creates VerticalTabs component

- components/useCommonToasters.tsx
We need period at the end of the sentence as rosibaj suggested
> Add period at the end of the sentences

- components/pages/submission-system/program-sample-registration/FileTable/index.tsx
> Set page size

- components/pages/submission-system/program-management/ManageProgramTabs.tsx
- uikit/Container/index.tsx
- uikit/Container/stories.tsx
> Fix overflow of container

- components/pages/submission-system/program-sample-registration/ErrorTable/index.tsx
> Hide pagination in registration error table

- components/pages/submission-system/program-management/ManageProgramTabs.tsx
- components/pages/submission-system/programs/ProgramsTable.tsx
- components/pages/submission-system/programs/index.tsx
Use container's loading spinner to keep the spinner centered
> Adjust min-height of the program list container

- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
> Set a minimum height to use the empty space

- components/pages/submission-system/program-sample-registration/index.tsx
Using updateQuery caused infinity rendering. I haven't found the real cause. Any comments are welcomed.
> Refetch instead of updateQuery because the latter is not stable

- components/pages/submission-system/program-sample-registration/ErrorTable/index.tsx
Do not send mutation when clear the registration file errors
> Handle clear in error box

- components/pages/submission-system/program-sample-registration/common.tsx
added text for new file names 
> change error for new file name

- components/pages/submission-system/SideMenu.tsx
changed "Clinical Submission" to "Submit Clinical Data"
> change label

- components/pages/submission-system/program-sample-registration/FileTable/index.tsx
- uikit/Affix/index.tsx
- uikit/Affix/stories.tsx
Very useful tool to make nested component sticky
> Use affix component to handle affix

- uikit/Table/NoDataComponent.tsx
Ultimately just adds a missing period
> ✏️ lets the NoData component handles title with default

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
- components/pages/submission-system/program-clinical-submission/SignOffValidationModal.tsx
- components/pages/submission-system/program-clinical-submission/SubmissionSummaryTable.tsx
- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-clinical-submission/types.tsx
- uikit/Table/index.tsx
- uikit/Table/stories.tsx
- uikit/Table/styledComponent.tsx
- configures the table in SignOffValidationModal to render diff data
- adds a `withRowBorder` prop for table
- introduces a variant system for table, starting with two values: `"DEFAULT"` and `"STATIC"`, for quick ways to set common prop defaults.
> ✨ configures the table in SignOffValidationModal to render summary data

- components/pages/submission-system/program-clinical-submission/ErrorNotification.tsx
- components/pages/submission-system/program-clinical-submission/gql/CLINICAL_SUBMISSION_FRAGMENT.gql
- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-clinical-submission/types.tsx
- global/utils/common.tsx
addresses feedbacks in https://github.com/icgc-argo/platform-ui/issues/659, see commits for changes
> 🐛 error download stuff (#659)

- uikit/Footer/index.tsx
change text to "Data Platform" for consistency 
> change to Data Platform

- components/pages/submission-system/program-clinical-submission/SignOffValidationModal.tsx
- components/pages/submission-system/program-clinical-submission/gql/APPROVE_SUBMISSION_MUTATION.gql
- components/pages/submission-system/program-clinical-submission/gql/SIGN_OFF_SUBMISSION_MUTATION.gql
- components/pages/submission-system/program-clinical-submission/gql/UPLOAD_CLINICAL_SUBMISSION.gql
- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-clinical-submission/types.tsx
- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
- global/utils/common.tsx
- loading state while sign-off in progress (with 2s fake delay)
- checks on mutation result to decide whether to redirect
> ✨ implements the redirect when submission signoff succeeds

- components/pages/submission-system/common.tsx
- components/pages/submission-system/program-clinical-submission/Instruction/FileTemplatesDownloadButton.tsx
- components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
- next.config.js
- uikit/Button/stories.tsx
- uikit/DropdownButton/index.tsx
- uikit/DropdownButton/stories.tsx
Implements the tsv template downloads
Also creates a `DropdownButton` component. Preview of this is available at: [here](https://5daa1ee36b66560008ba05fd--argo-ui-storybook.netlify.com/?path=/story/uikit-dropdownbutton--basic) (FYI @kcullion)
> ✨ clinical submission schema download

- components/pages/submission-system/common.tsx
Added time stamps after date in clinicalInfoArea.
>  added time stamps to info area

- components/pages/submission-system/SIDE_MENU_CLINICAL_SUBMISSION_STATE.gql
- components/pages/submission-system/SideMenu.tsx
- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/index.tsx
> 🐛 menu status should show error if there is schema error

- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
> 🐛 fixes sample_registration download

- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
> ✨ toasts when fails to clear registration

- uikit/form/Input/styledComponents.tsx
> Set min-width for input element

- components/NavBar.tsx
- components/pages/DefaultLayout.tsx
- components/pages/submission-system/join/JoinProgramLayout.tsx
- components/pages/submission-system/join/details.tsx
- components/pages/submission-system/join/joinProgramForm/index.tsx
- components/pages/submission-system/join/login.tsx
- components/pages/submission-system/layout.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- global/hooks/useAuthContext.tsx
- pages/logged-in.tsx
> Fix a bunch of issues found in demo

- components/pages/submission-system/common.tsx
- components/pages/submission-system/program-clinical-submission/gql/CLINICAL_SUBMISSION_FRAGMENT.gql
- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-clinical-submission/types.tsx
- global/utils/common.tsx
- Updated clinical_fragment and types to support updatedAt and updatedBy for signoff
- some light refactoring too
related to this PR: https://github.com/icgc-argo/platform-api/pull/95
> added upadtedAt and updatedBy

- components/ApplicationRoot.tsx
- components/pages/submission-system/program-management/ManageProgramTabs.tsx
- global/utils/getApolloCacheForQueries.tsx
Persists apollo client in react state so that the cache is retained throughout navigation
> ♻️ Persists apollo client through navigation

- components/pages/submission-system/layout.tsx
Just noticed this was removed, probably as a result of a bad conflict resolution.
> 🐛 puts back the missing scroll persistence

- components/pages/submission-system/program-clinical-submission/index.tsx
> ✨ disable validation when submission is already validated

- components/pages/submission-system/join/GET_JOIN_PROGRAM_INFO.gql
- components/pages/submission-system/join/JoinProgramLayout.tsx
- components/pages/submission-system/join/details.tsx
- components/pages/submission-system/join/joinProgramForm/index.tsx
- Set min-height of the form so no werid bumps as typing
- Change text of the step 2 so the user name is shown
- Handle unknown error
> Hanlde feedbacks of join program flow

- uikit/form/MultiSelect/Option.tsx
- uikit/form/MultiSelect/index.tsx
- uikit/form/MultiSelect/stories.tsx
- font-size
- line-height
- padding
> Update styles of multiselect

- components/pages/submission-system/join/details.tsx
> Set to step1 when email is incorrect

- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
sets the card height with flexbox
> 💄 implements the full-height card in clinical submission

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
- components/pages/submission-system/program-sample-registration/FileTable/index.tsx
Makes registration and submission data table display rows with 1-index
> 🐛 table row index number

- components/pages/submission-system/join/JoinProgramLayout.tsx
- components/pages/submission-system/join/details.tsx
- components/pages/submission-system/join/joinProgramForm/validation.tsx
- components/pages/submission-system/program-dashboard/index.tsx
> Style fixes for join program flow

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
Only show stat numbers when validated
> 🐛 no stat number when not validated

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
- uikit/Table/index.tsx
implements data table rendering for dcc preview (https://zpl.io/boPqBQG)
> ✨ implements dcc preview in FileRecordTable.tsx

- components/pages/submission-system/program-clinical-submission/Header.tsx
> 💄 updates reopen button style and content for non-dcc

- components/pages/submission-system/program-sample-registration/index.tsx
add back in missing submitter donor id col for downloaded file
> add donor id to downloaded file

- components/pages/submission-system/join/joinProgramForm/index.tsx
It's still required in back-end so not sure why was not set so
> 🐛 department is a required field in join program form

- components/pages/submission-system/modals/styledComponents.tsx
- components/pages/submission-system/program-form/ProgramForm.tsx
- global/hooks/useFormHook.tsx
make `useFormHook` more strict with a generic type on the data shape
> 🎨 stricter type for useFormHook

- components/pages/submission-system/program-form/ProgramForm.tsx
- global/constants/index.tsx
- global/hooks/useFormHook.tsx
- global/utils/form/validations.tsx
- package-lock.json
- package.json
installs `@types/yup` and matches up typings
> 🎨 adds yup typing

- components/pages/submission-system/join/details.tsx
- components/pages/submission-system/join/joinProgramForm/index.tsx
- components/pages/submission-system/join/joinProgramForm/validation.tsx
- global/hooks/useFormHook.tsx
join program form `department` field wasn't required by yup
> make department required for validation

- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-clinical-submission/gql/CLEAR_SUBMISSION_MUTATION.gql
- components/pages/submission-system/program-clinical-submission/types.tsx
- gql for clear submission
- added onlcick funcitons for button
> clear buttons hooked up for clinical submit

- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
> missed set loader false

- components/pages/submission-system/SideMenu.tsx
- uikit/SubMenu/index.tsx
don't run onClick if noChevron is selected
> only collapse My Programs when user is dcc or rdpc

- components/pages/submission-system/program-sample-registration/FileTable/index.tsx
- removes the Affix component instance wrapping the registration table header
> 🐛 removes sticky header

- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-clinical-submission/gql/CLINICAL_SUBMISSION_QUERY.gql
- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-clinical-submission/types.tsx
- removed prgram from CLINICAL_SUBMISSIONS_QUERY
- change programName -> programShortName
> :bug: fix programName -> programShortName

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-management/ManageProgramTabs.tsx
- global/hooks/useUrlParamState.ts
needs to serialize and deserialize data persisted to url as string. 
- make the `useUrlParamState` expect `serialize` and `deserialize` functions.
- `useUrlParamState` applies sanitization before serializing:
+ `"null"` gets sanitized to `null`
+ `"undefined"` gets sanitized to `undefined`
+ `""` gets sanitized to `undefined`
> 🐛 implements param serialization for useUrlParamState

- compose/clinical-bootstrap/sample-schema.json
just updating clinical sample schema
> 🐳 updates clinical sample schema

- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- components/pages/submission-system/program-sample-registration/types.tsx
Was going to standardize the page-wide loading state, but my OCD got caught by this...
> ♻️ refactors the registration loading states

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-clinical-submission/gql/CLINICAL_SUBMISSION_FRAGMENT.gql
- components/pages/submission-system/program-clinical-submission/types.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
- components/pages/submission-system/program-sample-registration/gql/REGISTRATION_FRAGMENT.gql
- components/pages/submission-system/program-sample-registration/index.tsx
- components/pages/submission-system/program-sample-registration/types.tsx
- changed the registration fileErrors display from banner to notification
- made appropriate changes for this ^
- msg -> message in clinical submission (for consistency)
- updated gqls as needed
connected to PR https://github.com/icgc-argo/platform-api/pull/111
-  tests are failing because schema updated ^
- `npm run test-gql-validation` is working in local setup
> update registration fileError banner to notification

- components/pages/submission-system/programs/index.tsx
rename query param #889
rename query param to activeTab for recent router changes 
> 🐛 rename query param

- components/pages/submission-system/program-dashboard/index.tsx
set justJoined state to false after dismissing banner #911
> 🐛 close welcome banner

- components/pages/user/ProgramAccessBox/index.tsx
show loader for whole DACO box and center it #300
> 💄 loader for DACO box

- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
This PR is updating messages for these two issues:
- https://github.com/icgc-argo/platform-ui/issues/903
- https://github.com/icgc-argo/platform-ui/issues/912
Did them both in one PR cause that made more sense :man_shrugging: 
> updated messages

- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
adds loading state for clinical registration upload button
> ✨ loading state for the clinical registration upload button

- components/pages/submission-system/ErrorNotification.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
change onClear prop to optional for error notifaction #924
removes on clear for clinical submission
> ✨ clear optional error notifcation

- components/pages/submission-system/ErrorNotification.tsx
- global/utils/clinicalUtils.ts
> make tsv row numbers start from 2

- uikit/package.release.json
removing some dependencies that isn't needed for uikit distribution
> 🔥 uikit distribution dependency cleanup

- components/NavBar.tsx
add active state for user menu item #892
> 💄 active state for user dropdown

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
- add border between rows with updates in clinical submission
> add border between updating rows

- uikit/package.release.json
6.10.0 doesn't exist 
https://www.npmjs.com/package/@types/react-table
> 🐛 fix react table types version

- components/pages/submission-system/ErrorNotification.tsx
- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- global/utils/clinicalUtils.ts
fixes the row mismatch in tsv export of error reports
> 🐛 fixes the error export row index

- components/pages/submission-system/join/JoinProgramLayout.tsx
- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- uikit/Tabs/index.tsx
Small changes, adding identifiers for e2e testing to use.
> ✨ Ids for E2E testing of Registration

- uikit/Table/index.tsx
- uikit/Table/stories.tsx
- uikit/Table/styledComponent.tsx
add optional full outside border
> 💄 table addition

- .env.schema
- README.md
- compose/README.md
> updates readme

- uikit/Icon/icons/collection/chevron_left.tsx
- uikit/Icon/icons/collection/chevron_up.tsx
- uikit/Icon/icons/index.tsx
add chevron left and chevron up
> 💄 chevron variations

- components/ApplicationRoot.tsx
- components/GdprMessage.tsx
- components/GdprMessageContainer.tsx
- global/constants/index.tsx
Adds gdpr message:
- persists acceptance to localstorage
> ✨ adds gdpr message

- components/pages/submission-system/ClinicalSubmissionProgressBar.tsx
- components/pages/submission-system/ProgressBar.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/index.tsx
Refactored the code for ClinicalSubmissionProgressBar for use in dashboard page and Clinical Submission page
> Refactor progress bar

- components/pages/submission-system/SampleRegistrationProgressBar.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
> ♻️ Refactor to add SampleRegistrationProgressBar

- components/GdprMessage.tsx
- global/constants/pages.tsx
- uikit/Link/index.tsx
- uikit/Link/stories.tsx
> adds privacy policy link to gdpr message

- components/pages/submission-system/ClinicalSubmissionProgressBar.tsx
- components/pages/submission-system/SampleRegistrationProgressBar.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
> ♻️ Adding programShortName as a prop

- components/pages/submission-system/ClinicalSubmissionProgressBar.tsx
- components/pages/submission-system/SampleRegistrationProgressBar.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-dashboard/ProgramWorkspaceStatus/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
> Program workspace status

- components/pages/submission-system/program-management/Users.tsx
- components/pages/submission-system/programs/ProgramsTable.tsx
> remove pagination

- components/pages/submission-system/programs/ProgramsTable.tsx
> fix pagesize

- components/pages/submission-system/program-dashboard/ProgramWorkspaceStatus/index.tsx
> ✨ Added links

- components/pages/submission-system/program-dashboard/ProgramWorkspaceStatus/index.tsx
> 👌 One line span change

- compose/clinical-bootstrap/sample-schema.json
> 🐳 update sample schema

- components/pages/submission-system/SubmissionSystemLockedNotification.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- components/pages/submission-system/program-management/index.tsx
Looks like UI design had the notification with no close for certain pages...
> remove close from submission pages

- package-lock.json
- uikit/Modal/index.tsx
- uikit/Modal/stories.tsx
change the modal action button to be optional
defaults to visible
> 💄 modal optional action button

- components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
> 💚 Creating ids for buttons

- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
> 💚 Creating selenium hooks clear

- uikit/Modal/index.tsx
- uikit/Modal/stories.tsx
add option for custom modal container
> add option for custom modal container

- components/pages/submission-system/ErrorNotification.tsx
- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- compose/clinical-bootstrap/sample-schema.json
> ✅ Adding ids for Selenium and updating sample schema

- components/pages/submission-system/program-clinical-submission/Header.tsx
Change approval toast to remove queue language. 
> update approval toast text

- components/pages/submission-system/common.tsx
- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
- components/pages/submission-system/program-sample-registration/FileTable/index.tsx
> 🐛 fixes the row number and change header

- components/pages/user/AccessKeyBox/index.tsx
- uikit/ClipboardCopyField/index.tsx
- uikit/ClipboardCopyField/stories.tsx
> 💚 Adding Button Ids on User Page

- components/pages/user/AccessKeyBox/index.tsx
- uikit/ClipboardCopyField/index.tsx
> 💚 Adding ids for key expiry and key

- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/SignOffValidationModal.tsx
> 💚 Adding ids to approve and reopen buttons

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
> 🐛 Validation error should go to incorrect tab

- components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
Another icon needs to have variable color dependent on the state of `upload enabled`.
> Adding state-dependent color for another icon

- components/pages/login.tsx
> Landing page beta

- components/GdprMessage.tsx
- components/pages/submission-system/join/JoinProgramLayout.tsx
- components/pages/submission-system/join/details.tsx
- components/pages/submission-system/join/login.tsx
- global/constants/index.tsx
- pages/logged-in.tsx
- pages/login.tsx
Implements join flow redirects with google login `redirectPath` prop
Removes redirect logic from localStorage
Corrects some typos because I can't help myself
- *branched `940-integrate-ego-redirect`
> ✨ Remove localStorage key from join flow redirect. Correct some typos

- .env.schema
- components/pages/login.tsx
- global/config.ts
- next.config.js
> Adding links

- components/GoogleLoginButton.tsx
- components/NavBar.tsx
- components/pages/login.tsx
- components/pages/submission-system/join/JoinProgramLayout.tsx
- components/pages/submission-system/join/details.tsx
- components/pages/submission-system/join/login.tsx
- global/hooks/useAuthContext.tsx
- global/utils/common.tsx
- pages/_app.tsx
- pages/login.tsx
- pages/submission/program/join/details/[inviteId].tsx
- uikit/Button/GoogleLogin/index.tsx
- parses redirect url in _app ego token flow to ensure isOauth param does not get added to join inviteId
- adds util function for creating redirect urls
- adds wrapper for GoogleLoginButton to log out on click without redirect to root
> 🐛 940 fix redirect on join flow

- components/pages/user/index.tsx
Corrects field retrieved from graphql response
> 🐛 Correct apiKey retrieved from user data

- components/pages/submission-system/SchemaInvalidSubmissionNotification.tsx
- components/pages/submission-system/SubmissionSystemLockedNotification.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- components/pages/submission-system/program-management/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- removes invalid clinical submission message from sample registration
- removes invalid clinical submission and workspace locked messages from manage program
- updates workspace locked message to more generic text, removes docs site link
- fixes typo in `SchemaInvalidSubmissionNotification` component name
> 🐛1125 correct clinical banner placement

- components/pages/user/ApiTokenBox/index.tsx
Updates Api Token generation message with new copy.
> 💬 Update api token message

- components/pages/submission-system/modals/common.tsx
Removes COLLABORATOR as default role when adding a new user.
- form will display an error if a role is not selected.
> 🐛 Remove collaborator as default new user role.

- components/pages/submission-system/programs/ProgramsTable.tsx
Use program array size to set pagesize
> use number of programs to set pageSize

- components/pages/submission-system/modals/common.tsx
- global/utils/form/validations.tsx
Allow RoleKey to be nullable to prevent schema error when a role is not selected after opening the menu.
> 🐛 Fix role required error display

- components/NavBar.tsx
- components/pages/submission-system/join/login.tsx
- components/pages/submission-system/program-form/ProgramForm.tsx
- pages/_app.tsx
- pages/login.tsx
- uikit/Button/GoogleLogin/index.tsx
Adds redirect logic to Navbar login button
- including for private and public paths, and no path (this should redirect to `logged-in`)
- removes `/` default value for GoogleLogin `redirectPath`, this caused a 403 on oauth because it add a trailing `/` when the original path was `/login`
- corrects a typo on the Create Program form
> ✨Add redirect logic for public paths

- components/Footer.tsx
- components/pages/401.tsx
- components/pages/404.tsx
- components/pages/500.tsx
- components/pages/contact.tsx
- components/pages/login.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
- components/pages/submission-system/program-dashboard/CompletedClinicalData/index.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
- components/pages/submission-system/program-dashboard/MolecularDataSummary/index.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- components/pages/user/ApiTokenBox/index.tsx
- components/pages/user/ProgramAccessBox/DacoAccessStatusDisplay.tsx
- global/constants/pages.tsx
- pages/maintenance.tsx
> Add documentation links

- Jenkinsfile.groovy
- package.json
- uikit/.npmrc
💩 test
💩 more test
💩 final test
💚 cleanup
> 💚 fixes uikit publish

- uikit/Modal/index.tsx
> 💄 Force max height on modal for scrolling

- Jenkinsfile.groovy
updates CI to publish uikit off `develop`
> 👷 publish uikit off develop

- components/pages/submission-system/modals/addUser/index.tsx
Removing the height and scroll on the add users form section as it was overriding the parent scroll.
> 💄 Remove child scroll and maxheight

- .env.schema
- components/Footer.tsx
- components/pages/401.tsx
- components/pages/404.tsx
- components/pages/500.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- components/pages/submission-system/program-management/index.tsx
- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
- pages/maintenance.tsx
- uikit/Footer/index.tsx
> 🐛 Fixking up some bugs with links

- uikit/package.release.json
> 🔖 Bump uikit to 1.0.10

- components/pages/login.tsx
just moving the banner position
> 💄 repositions beta banner

- components/pages/submission-system/modals/addUser/index.tsx
> 🐛 Non-duplicate emails are errors if there is a different duplicate email

- components/pages/submission-system/modals/addUser/index.tsx
> 1207 email case sensitivity and message bug

- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
> copy change to toast

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
-  file tabs would not get correct priority sorting unless the user had just completed uploading files.     
- modified the condition to stop this from happening.
- prior to getting to the submission validated phase, every file tab without errors was getting the 'WARNING' status, even for files with no uploaded records. as a result, actual 'WARNING' tabs were not getting priority over files with no status. 
- applied the 'none' status so real warning tabs could get actual priority.
> Fix Tab Priority Logic Bug

- uikit/tsconfig.json
> change es target for uikit tsconfig

- uikit/package.release.json
> bump uikit version

- uikit/Footer/index.tsx
> 🐛 Fixing footer link line break

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-sample-registration/Instructions/RegisterSamplesModal.tsx
> 💬 Adding text change to toasts.

- components/pages/submission-system/program-management/PROGRAM_QUERY.gql
- consume isDacoApproved from gateway
> add isDacoApproved to query

- .env.schema
- components/pages/contact.tsx
- global/config.ts
- package-lock.json
- package.json
> 336 contact redesign

- global/config.ts
> ✏️ Fixing ReCAPTCHA typo

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
> 🐛 fixes cell layout

- next.config.js
> 🐛 Adding RECAPTCHA_SITE_KEY to next.config.js

- components/pages/submission-system/program-dashboard/DonorReleaseSummary/index.tsx
- components/pages/submission-system/program-dashboard/ProgramWorkspaceStatus/index.tsx
- Modified css to adhere [to new spec](https://github.com/icgc-argo/platform-ui/issues/1243)
> Dashboard card style updates

- components/Footer.tsx
- uikit/Footer/index.tsx
Updates footer links to icgc-argo resource links
Adds missing target prop to last footer link
> 💬 Updating footer links

- components/pages/submission-system/ClinicalSubmissionProgressBar.tsx
- components/pages/submission-system/program-dashboard/DonorReleaseSummary/index.tsx
- components/pages/submission-system/program-dashboard/ProgramWorkspaceStatus/index.tsx
Sorry for all the PRs @hlminh2000  🙈
- made the width for the bar as a parameter so it doesn't affect the bar's appearance on other pages
> pending approval variable width

- components/pages/submission-system/program-dashboard/StatsBar/DASHBOARD_SUMMARY_QUERY.gql
- components/pages/submission-system/program-dashboard/StatsBar/index.tsx
> ✨ Summary Stats Data Hookup

- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.gql
- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
- components/pages/submission-system/program-dashboard/StatsBar/index.tsx
- components/pages/submission-system/program-dashboard/common.tsx
> fix query to retrieve 500 and polling

- public/robots.txt
> ✨ Beep Boop adding robots.txt

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorReleaseSummary/index.tsx
- React-table depends on the accessor name for auto sorting, property names were outdated so sorting didn't work for some columns 
- also: small css fix for a dashboard card
> Update dashboard table accessors

- components/ApplicationRoot.tsx
persist apollo client through navigation
> 🐛 persist client through renders

- components/pages/submission-system/program-dashboard/StatsBar/index.tsx
> 👌 QA review changes

- uikit/package.release.json
publish latest uikit with table select fix
> 🔖 uikit 1.0.12

- components/pages/user/index.tsx
- global/hooks/useAuthContext.tsx
- global/utils/egoJwt/index.tsx
Refresh jwt 30sec before expiry
Add validity check to all eogJwt util functions
Remove polling in user query (was for dev testing)
> 🐛 Add validity checks to egoJwt util funcs, refresh token early

- components/pages/contact.tsx
> 🐛 Contact page UI fixes

- uikit/package.release.json
> 🔖 uikit rc 1.0.13

- components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
- components/pages/submission-system/program-dashboard/DonorReleaseSummary/index.tsx
- components/pages/submission-system/program-dashboard/StatsBar/index.tsx
Limits polling to 30 seconds where appropriate
> ✨ implements polling timeout

- global/utils/common.tsx
- pages/_app.tsx
Prevents creating redirect when ctx path is undefined.
> 🐛 Prevent undefined redirect path

- components/pages/submission-system/donor/DonorFileCard/index.tsx
- components/pages/submission-system/donor/DonorFileCard/stories.tsx
> 1270 donor file card

- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
- package-lock.json
This was causing the table to flash randomly between different states
> remove notify on change

- components/pages/submission-system/donor/DonorDataTable/index.tsx
> 👌 Donor Data Table Feedback Changes

- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
> ✨ Adding buttons to Dashboard Donor Data Summary

- components/pages/submission-system/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTableStatArea.tsx
- better loading state implementation
- propagate the css into DonorStatsArea
> ✨ better loader implementation

- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
> 👌 Donor Data Summary Buttons

- uikit/package.release.json
> Bump uikit 1.1.0

- uikit/Pipe/index.tsx
> 🐛 Fixing pipe font and spacing

- global/utils/egoJwt/index.tsx
- package-lock.json
- package.json
- updates `@icgc-argo/ego-token-utils` and cleans up some resulting type errors
> ⬆️ updates ego-token-utils and fixes up some typeings

- uikit/package.release.json
> 🔖 uikit 1.2.0

- components/pages/submission-system/donor/DonorSummaryStats/index.tsx
> ✨ Donor Summary Card Feedback

- components/Footer.tsx
- uikit/Footer/index.tsx
Retrieve api version from gateway
Update footer date.
> ✨ Retrieve api version from gateway, update footer copyright

- uikit/package.release.json
> 🔖 uikit 1.3.0

- uikit/package.release.json
> 🔖 uikit 1.4.0

- components/pages/file-repository/StatsCard/StatItem.tsx
Adds minimal responsiveness for stats bar items
> 💄 Minimal responsiveness for statsBar

- components/pages/file-repository/SimpleBarChart/index.tsx
Adds `files` to chart tooltips
Capitalizes chart titles
> 💬 Tooltip and chart text mods

- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/index.tsx
- uikit/PageLayout/index.tsx
- Adjust styles for a 'custom' facet component on the page
- Make the sidebar of the page wider
> Styling Adjustments for File Repo Facet Bar

- components/pages/submission-system/donor/ClinicalTimeline/timeline.tsx
> fix magic number

- components/pages/file-repository/FacetPanel/index.tsx
small css change has resolved the bug
> Fix scrollbar issue on facetpanel

- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
not needed atm, so the buttons have been commented out
> temporarily comment out download buttons

- components/pages/Homepage/index.tsx
- components/pages/user/ApiTokenBox/index.tsx
- components/pages/user/ProgramAccessBox/DacoAccessStatusDisplay.tsx
> 🔗 update links 🔗

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
> case insensitivity on uploaded file names

- .gitignore
- components/Footer.tsx
- components/NavBar.tsx
- components/pages/403.tsx
- components/pages/404.tsx
- components/pages/500.tsx
- components/pages/contact.tsx
- components/pages/error.tsx
- components/pages/login.tsx
- components/pages/submission-system/SchemaInvalidSubmissionNotification.tsx
- components/pages/submission-system/program-clinical-submission/Header.tsx
- components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
- components/pages/submission-system/program-dashboard/CompletedClinicalData/index.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/EmptyDonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/MolecularDataSummary/index.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- components/pages/submission-system/program-management/index.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- components/pages/user/ApiTokenBox/index.tsx
- components/pages/user/ProgramAccessBox/DacoAccessStatusDisplay.tsx
- global/config.ts
- global/constants/docSitePaths.tsx
- global/constants/pages.tsx
- next.config.js
- package.json
- pages/maintenance.tsx
- tsconfig.json
- uikit/Footer/index.tsx
- refactors the `pages.tsx` file to contain only internal pages
- remove links to internal pages in the maintenance page
- improve responsiveness for the error pages
- adds some setup to export the maintenance page as a static web bundle.
> Maintenance page static build

- components/pages/Homepage/index.tsx
> :bug: center the data callouts

- global/hooks/useAuthContext.tsx
- global/hooks/useProgramCheckEffect.tsx
Adds a `isLoggingOut` state to AuthContext to prevent subsequent checks for program access  when a user clicks logout().
> 🐛 Add logging out state to prevent unnecessary program auth check

- components/pages/submission-system/program-dashboard/index.tsx
Adds program id, text change to program welcome message
> 💬1393 - Add program id to welcome message

- components/pages/contact/index.tsx
- Make the form container flow down on smaller screen
- Removes some code noise
> Improve responsiveness of contact page

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- Core Fields -> Core Completion
> update header for consistency

- global/constants/index.tsx
- pages/_app.tsx
- pages/login.tsx
Disables `/login` path, redirects to root.
Some code is commented out as this is a temporary change until a decision is made for keeping a dedicated `/login` path flow.
> 🐛1486 - redirect to root

- .env.schema
- components/pages/MaintenancePage.tsx
- global/config.ts
- next.config.js
- pages/_app.tsx
- pages/maintenance.tsx
- adds an environment variable to toggle maintenance mode to show the maintenance page for every request
> :sparkles: adds maintenance mode toggler

- components/pages/submission-system/program-dashboard/CompletedClinicalData/index.tsx
- components/pages/submission-system/program-dashboard/MolecularDataSummary/index.tsx
Change 'No data found' text to 'Coming Soon'
> Change to NoData copy

- components/NavBar.tsx
- components/pages/error.tsx
- components/pages/submission-system/layout.tsx
- rename `hideLink` to `hideLinks` in `NavBar`
- hides file repo link if `hideLink` is true in `NavBar`
> :bug: hides file repo link if hideLinks in navbar

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
show all FileRecordTable rows until pagination implemented
> show all FileRecordTable rows until pagination implemented

- components/pages/contact/CREATE_JIRA_TICKET.gql
- components/pages/contact/index.tsx
- updates the UI to submit jira ticket against the new mutation with recaptcha
> :sparkles: integrates with new mutation that uses recaptcha

- global/config.ts
- the transformation is incorrect and we'd rather not have it
> :bug: remove transformation of ego public key config

- components/pages/submission-system/SampleRegistrationProgressBar.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
> show toast on failed upload mutations

- components/pages/file-repository/FileTable/index.tsx
Increases hover area for file download cell tooltip to decrease jumpiness
> 💄 1381 - Increase hit area for tooltip

- components/pages/file-repository/FileTable/dummyData.tsx
- components/pages/file-repository/FileTable/index.tsx
- initial setup for pagination state management overrides 
- these live in the filetable component
- top of table shows which rows you're viewingbased on the page number
> Add pagination only to filetable component

- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/QueryBar/QueryBarContainer.tsx
- components/pages/file-repository/QueryBar/index.tsx
- components/pages/file-repository/QueryBar/stories.tsx
- components/pages/file-repository/hooks/useFiltersContext.tsx
- components/pages/file-repository/utils/index.ts
- components/pages/file-repository/utils/types.ts
- uikit/Facet/NumberRangeFacet/index.tsx
- uikit/Facet/NumberRangeFacet/stories.tsx
- uikit/Facet/index.tsx
- uikit/Facet/stories.tsx
- uikit/OptionsList/ViewAmountController.tsx
- uikit/OptionsList/index.tsx
- uikit/OptionsList/stories.tsx
- lift state out of OptionsList
- toggle facets
- unselect facet from filter values
- selectAll/deselectAll facets
- url state is synced
> ✨ Integrate filter state with facets

- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/FileTable/index.tsx
Disables some features that won't be available for initial release.
> 🚧 1553 - Disabling some features for initial File Repo release

- components/pages/file-repository/StatsCard/STATS_BAR.gql
- components/pages/file-repository/StatsCard/StatItem.tsx
- components/pages/file-repository/StatsCard/index.tsx
- primary sites is left out as not currently available
> stats bar data hookup

- components/pages/file-repository/FileTable/index.tsx
- moves the file repo table states into smaller hooks
- refactors selected row state to. contain object ids directly
- fixes the total page calculation
> ♻️ move the file repo table states into smaller hooks

- components/ApplicationRoot.tsx
- components/Footer.tsx
- components/pages/file-repository/FileTable/TsvDownloadButton.tsx
- components/pages/file-repository/FileTable/index.tsx
- components/pages/file-repository/utils/types.ts
- components/pages/submission-system/common.tsx
- global/constants/gatewayApiPaths.tsx
- global/utils/getApolloCacheForQueries.tsx
- uikit/DropdownButton/index.tsx
- uikit/Table/index.tsx
- extracts all the gateway api paths to constants
- refactors the tsv download button to own component cause IT'S GONNA BE HUGE~~~
- reimplements and refactors the table selection state to a reusable hook
- Implements the manifest download.
- minor style and content update for the tsv download button
> file repo manifest download

- components/pages/file-repository/FacetPanel/FILE_REPOSITORY_FACETS_QUERY.gql
- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/FacetPanel/types.ts
- components/pages/file-repository/types.ts
- uikit/OptionsList/index.tsx
Adds `analysis_tools` and `data_category` to Repo Facets.
- truncates + adds tooltip for long option names
- updates mapping for `variant_class`
> ✨ 1598 - Add analysis_tools and data_category

- components/pages/file-repository/FacetPanel/FILE_REPOSITORY_FACETS_QUERY.gql
- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/FacetPanel/types.ts
- components/pages/file-repository/types.ts
Adds `workflow_name`, `specimen_type` and `specimen_tissue_source` to facets
> ✨ Adds analysis and workflow facets

- components/GdprMessage.tsx
- components/pages/Homepage/common.tsx
- components/pages/Homepage/index.tsx
issues:
https://github.com/icgc-argo/platform-ui/issues/1624
https://github.com/icgc-argo/platform-ui/issues/1621
> update homepage and cookie banner messages

- components/pages/file-repository/FacetPanel/SearchResultsMenu.tsx
- components/pages/file-repository/FacetPanel/index.tsx
- uikit/form/Input/index.tsx
Adds case-insensitive search.
Modifies search results menu state
Fixes scrollbar overlap in windows chrome
Decrease search input icon size
> 🐛 1517 - feedback

- components/pages/file-repository/FacetPanel/index.tsx
> :bug: remove the toggling effect when clicking on input

- components/pages/Homepage/index.tsx
> :sparkles: use internal link for file repo

- components/pages/Homepage/index.tsx
- global/constants/docSitePaths.tsx
> 💬 1641 - homepage announcement

- components/pages/Homepage/common.tsx
> :bug: magic fix for the inconsistent style

- uikit/AppBar/index.tsx
- uikit/utils/useClickAway/index.tsx
> 🎨 typing for useClickAway hook

- components/pages/file-repository/FacetPanel/FILE_REPOSITORY_FACETS_QUERY.gql
- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/FacetPanel/types.ts
Adds `data_type` facet to File Repo
Will be tested before deciding to remove `data_category`
> ✨ 1658 - Add data type facet

- .env.schema
just an env schema update. Not sure if readme needs any update
> :bulb: updates env schema

- global/hooks/useUrlParamState.ts
param state hook was firing twice, check for initial render to selectively update
thanks for the fix @minh
> check for initial render

- global/hooks/useUrlParamState.ts
- package.json
> 🔖 Rc/1.60.0

- components/pages/submission-system/program-form/validations.tsx
> fix commitment level validation

- components/pages/user/ProgramAccessBox/DacoAccessStatusDisplay.tsx
- components/pages/user/ProgramAccessBox/index.tsx
Style update for member access display.
Enable `View Files` link from Daco access display box.
> 💄 Styling for user member access

- components/pages/file-entity/AssociatedDonors/index.tsx
> fix small typo in file entity page

- uikit/Icon/icons/index.tsx
> add reset icon

- components/pages/submission-system/program-form/ProgramForm.tsx
- this way when the value doesn't actually change, the save button remains disabled
> add equality check when form value is a number

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
> 💄 1055 - Reorder clinical tabs

- components/pages/file-repository/FacetPanel/SearchResultsMenu.tsx
- TIL we have predefined shadow styles in our global theme object :) 
> add shadow to search results dropdown

- components/pages/file-repository/FileTable/index.tsx
- components/pages/submission-system/program-management/UsersTable.tsx
- components/pages/submission-system/programs/ProgramsTable.tsx
- uikit/Icon/InteractiveIcon/index.tsx
- uikit/Icon/InteractiveIcon/stories.tsx
- uikit/Icon/icons/index.tsx
- uikit/Icon/index.tsx
- uikit/Tooltip/index.tsx
- removed incorrect property value on icon which was causing an error
- combined tooltip with icon ( there was already a component called interactive icon, just moved it out of the table folder and extended onto it )
- fixed flickering issue that would sometimes happen with the tooltip when hovering
- replaced instances of tooltip  + icon with InteractiveIcon
> make interactive icon

- uikit/OptionsList/index.tsx
- uikit/Tag/index.tsx
make the options blue if they're selected
> highlight selections in optionslist

- uikit/package.release.json
bump uikit
- minor added an icon
> bump uikit

- uikit/SystemAlert/index.tsx
- uikit/SystemAlert/stories.tsx
Creates SystemAlert component (no integration to platform)
Assumes an api response for notifications: `[{ level: AlertLevel; title: string; message?: string; dismissable: boolean; }, ...]`
> ✨ 1666 - Add SystemAlert component

- uikit/package.release.json
> 🔖 uikit 1.7.0

- uikit/Table/SimpleTable/index.tsx
> set highlight to false on simple table

- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
The old vs new value view in the file difference preview should _also_ be accessible to data submitters.
But data submitters are not meant to see the prioritized row view, that is still for dcc members only.
> check if user is datasubmitter for file diff view

- uikit/SystemAlert/index.tsx
- uikit/SystemAlert/stories.tsx
- added some new knobs to the system Alert story
- the icon needs to stay affixed to the left of the message at a constant distance, changed to a flexbox layout to achieve this
> redo systemAlert with flexbox, add new knobs

- components/NavBar.tsx
- uikit/AppBar/index.tsx
fixes the badge rendering problem. (looks like react's diffing algorithm got confused by some of the extra divs...)
> :bug: fixes the badge rendering

- components/pages/submission-system/programs/ProgramsTable.tsx
cell wrapper changes alignment based on whether the rows span multiple lines or not
> add cell wrapper to programs table

- components/pages/submission-system/ErrorNotification.stories.tsx
- components/pages/submission-system/ErrorNotification.tsx
- components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
- components/pages/submission-system/program-clinical-submission/FilesNavigator/index.tsx
- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- components/pages/submission-system/program-clinical-submission/gql/CLINICAL_SUBMISSION_FRAGMENT.gql
- components/pages/submission-system/program-clinical-submission/types.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- compose/.env.schema
add warning variant to submission error table
add warning record state and change bg color
add data warnings to gql queries & type
> add warning variant to submission error table

- components/pages/Homepage/index.tsx
- components/pages/contact/index.tsx
- components/pages/file-repository/index.tsx
- components/pages/head.tsx
- components/pages/submission-system/layout.tsx
- components/pages/submission-system/program-clinical-submission/index.tsx
- components/pages/submission-system/program-dashboard/index.tsx
- components/pages/submission-system/program-management/index.tsx
- components/pages/submission-system/program-sample-registration/index.tsx
- components/pages/team.tsx
- components/pages/user/index.tsx
- pages/repository/index.tsx
- Subtitles added to ICGC ARGO for various site pages
> Add Page Titles Throughout site

- components/pages/submission-system/program-form/validations.tsx
- global/constants/index.tsx
- let "INTL" be a valid country code when making a shortname
> add international to the country code validation

- global/hooks/useUrlParamState.ts
Add `router.asPath` as dependency for updating tab useEffect
Consistent website behaviour, doesn't save state on reloading the page.
> URL param hook breaking navigation

- components/pages/user/ApiTokenBox/index.tsx
- components/pages/user/ProgramAccessBox/USER_PROGRAM_LIST_QUERY.gql
- components/pages/user/ProgramAccessBox/index.tsx
- components/pages/user/common.tsx
- components/pages/user/gql/PROFILE.gql
- components/pages/user/index.tsx
- global/utils/egoJwt/index.tsx
- package-lock.json
- package.json
User Profile Page
- add program membership type to table (from program service not JWT)
- add user membership tag if they are not a `Collaborator`
- updated `ego-token-utils` minor version
- merged two gql queries for profile page
> User page updates

- components/pages/file-repository/FacetPanel/index.tsx
better handle conditional facet, clean up logic
> file repo bug - not logged in breaks the page

- Jenkinsfile.groovy
**Docker Registry change for platform-ui image**
> Docker registry change

- uikit/Tabs/index.tsx
> change tab colour from accent1 to secondary (green to blue)

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.gql
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
adds Mutect2 to donor summary table
> add Mutect2 to donor summary table

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
update mutect column ID on program dashboard
> ✏️ update mutect column ID

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
function added to convert our donor data table paging sort to a sort object React Table understands so default sort is reflected in the UI
> donor table default sort ui

- components/pages/submission-system/donor/ClinicalTimeline/Header.tsx
- components/pages/submission-system/donor/ClinicalTimeline/Samples.tsx
- components/pages/submission-system/donor/ClinicalTimeline/Timeline.tsx
- components/pages/submission-system/donor/ClinicalTimeline/Treatment.tsx
- components/pages/submission-system/donor/ClinicalTimeline/index.tsx
- components/pages/submission-system/donor/ClinicalTimeline/stories.tsx
- components/pages/submission-system/donor/ClinicalTimeline/util.ts
Clinical Timeline: Treatment tab update 
visible in storybook in: http://localhost:6006/?path=/story/components-pages-submission-system-donor-clinicaltimeline--basic
> Clinical Timeline updates

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
> add immunotherapy to submission page

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
> move immunotherapy above radiation

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
> add family history tab

- package.json
This release adds a `family history` tab on the clinical submission page.
> Release Candidate 1.92.1

- components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/mockData.ts
- components/pages/submission-system/program-dashboard/ClinicalChart/types.ts
- components/pages/submission-system/program-dashboard/ClinicalChart/utils.ts
- change `createdAt` to `coreCompletionDate` for the clinical chart
- update test data
> #628 add core completion date

- components/pages/file-repository/FacetPanel/FILE_REPOSITORY_FACETS_QUERY.gql
- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/FacetPanel/types.ts
- components/pages/file-repository/charts/PrimarySiteBarChart/PRIMARY_SITE_CHART.gql
- components/pages/file-repository/charts/PrimarySiteBarChart/index.tsx
- components/pages/file-repository/index.tsx
- components/pages/file-repository/types.ts
this PR is blocked by a PR on platform-api. the build here is failing because the API changes aren't merged
---
- add primary site to file repository facet panel
- add a primary site chart to the file repository page
> ✨ add primary site to file repo

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
This PR adds a new tab `comorbidity` to the submission page. 
> add comorbidity tab

- components/pages/Homepage/index.tsx
- package.json
This PR adds a new tab `comorbidity` on clinical submission page. 
> Release Candidate 1.95.0

- uikit/package.release.json
> bump uikit version - 1.9.1

- package-lock.json
- package.json
Ego 4 has new user structure in jwt, ego-token-utils lib was updated
> ⬆️  Upgrading ego-token-utils for ego v4

- components/pages/submission-system/program-dashboard/ClinicalChart/index.tsx
- add polling to clinical charts so they update like the donor summary table.
> 🐛 #1903 clinical chart doesn't update

- uikit/package.release.json
> bump uikit version - 1.10.0

- components/pages/file-repository/FileTable/TsvDownloadButton.tsx
- components/pages/file-repository/types.ts
- components/pages/file-repository/utils/constants.tsx
- global/constants/gatewayApiPaths.tsx
- add TSV download on file repository table
API PR: https://github.com/icgc-argo/platform-api/pull/404
> ✨ add file table TSV download

- uikit/form/Input/index.tsx
- uikit/form/Input/stories.tsx
- uikit/form/common.tsx
The only visible change is a blue halo when the field is focused. Everything else should work the same (or better, accessibility wise).
> ensure consistency at Input for blur and focus from FormControl

- components/pages/Homepage/index.tsx
- remove registration announcement on homepage
> 🔥 remove registration announcement on homepage

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
This PR adds a new `biomarker` tab on clinical submission page. 
> add biomarker tab on clinical submission page

- components/pages/submission-system/modals/addUser/index.tsx
- components/pages/submission-system/modals/styledComponents.tsx
- uikit/Progress/index.tsx
- uikit/theme/defaultTheme/button.tsx
- uikit/theme/defaultTheme/colors.tsx
- uikit/theme/defaultTheme/progress.tsx
> add closed state and center first and last items a little better

- uikit/Button/constants.tsx
- uikit/Button/index.tsx
- uikit/Button/styled.tsx
- uikit/Button/types.ts
- uikit/theme/defaultTheme/button.tsx
Reverts unnecessary changes to the button
> revert 'link' button (#1975)"

- uikit/package.release.json
Adds a Textarea counter, and fixes a fatal bug in Notifications (when Uikit is imported as a library)
> bump uikit version - 1.10.6

- package.json
Fixed version number for this release:
https://github.com/icgc-argo/platform-ui/pull/1980
> Versioning 1.100.0

- components/pages/file-repository/FileTable/TsvDownloadButton.tsx
- global/hooks/useAuthContext.tsx
Platform API requires authorization for downloads, so a file download action was added in the auth context to fetch a download with the JWT authorization header and handle getting the browser to download the file.
> Ability to download with auth header

- components/pages/file-entity/DataAndAnalysis/index.tsx
- components/pages/file-entity/dummyData.tsx
- components/pages/file-entity/types.tsx
- components/pages/file-repository/FileTable/TsvDownloadButton.tsx
- global/hooks/useAuthContext.tsx
- package.json
- File Page would crash for files with a workflow name/version. Fixed the expected data structure to prevent crash on page render.
> Release Candidate 1.100.2

- components/pages/file-repository/FileTable/TsvDownloadButton.tsx
- package.json
Adds a new `surgery` tab on clinical submission page. 
> Release Candidate 1.100.3

- uikit/form/FormCheckbox/stories.tsx
- uikit/form/FormRadio/index.tsx
- uikit/form/FormRadio/stories.tsx
- uikit/form/RadioCheckboxGroup/RadioCheckContext.tsx
- uikit/form/RadioCheckboxGroup/index.tsx
- uikit/form/common.tsx
adds disabled state and style to the radio checkbox group section
> add disabled state, style and stories

- uikit/form/Textarea/index.tsx
these changes ensure the textarea counter is aware of values being pre-filled upon component mount.
> make textarea counter work when value is prefilled

- .storybook/PropTypesTable/ReactTableContainer.tsx
- README.md
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.gql
- components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
- package-lock.json
- package.json
- uikit/Button/index.tsx
- uikit/DropdownPanel/index.tsx
- uikit/DropdownPanel/stories.tsx
- uikit/Icon/InteractiveIcon/index.tsx
- uikit/Icon/icons/collection/filter.tsx
- uikit/Icon/icons/index.tsx
- uikit/Table/reactTableDefaultStyle.tsx
- uikit/Table/styledComponent.tsx
- uikit/Tooltip/index.tsx
- uikit/Tooltip/stories.tsx
- uikit/form/FormCheckbox/stories.tsx
- uikit/form/FormRadio/index.tsx
- uikit/form/FormRadio/stories.tsx
- uikit/form/Input/index.tsx
- uikit/form/RadioCheckboxGroup/RadioCheckContext.tsx
- uikit/form/RadioCheckboxGroup/index.tsx
- uikit/form/Select/index.tsx
- uikit/form/Textarea/index.tsx
- uikit/form/common.tsx
- uikit/package.release.json
Includes new DropdownPanel UIKit component, and introduces filters to the Donor Summary Table (#1983)
> 🔖 Release Candidate 1.100.4

- uikit/form/MultiSelect/index.tsx
Fulfils the requirements from ticket https://github.com/icgc-argo/dac-ui/issues/93 for `single` selection autocomplete dropdown. 
Preview Storybook: https://fix-multiselect-integration--argo-ui-storybook.netlify.app/?path=/story/uikit-form-multiselect--basic
> improve Multiselect "single" functionality

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
* Connect dashboard table filters to API for `Sanger VC` and `Mutect2 Status` columns
* Refactor dashboard table filter options lists to reduce repeated code
> ✨ Dashboard Table Filters for Sanger VC and Mutect2 VC Status (#2018 #2019)

- package.json
- uikit/SystemAlert/index.tsx
- uikit/SystemAlert/stories.tsx
Allow links to be shown in the message body of SystemAlerts.
> Hotfix 1.101.4 - Links in SystemAlert messages

- uikit/form/MultiSelect/index.tsx
- add name attribute to multiselect text input in the hopes it'll fire a change event on autocomplete in daco-ui
- for **single** multi-selects, add a change event that is exposed/bubbles to outer components.
- platform-ui didn't have issues in my testing ('create program' page in the UI & 'join program' in storybook)
re: https://github.com/icgc-argo/dac-ui/issues/211
> add name to input in multiselect

- uikit/form/MultiSelect/index.tsx
adjusting this PR https://github.com/icgc-argo/platform-ui/pull/2053
> change multiselect single value to array

- package-lock.json
- package.json
version bump to trigger a QA build
> 🔖 Release Candidate 1.101.6

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.gql
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
- uikit/DropdownPanel/index.tsx
* Update Program Donor Summary GQL query to fetch new filter count aggregations
* Fetch filter counts and display them beside each option on dashboard table dropdown filters
* Fix a bug in DropdownPanel component preventing the number `0` from appearing as a stylized count beside an option
> 👽️ Connect Dashboard Dropdown Filters to New Aggregations (#2046)

- uikit/package.release.json
relevant PRs
- https://github.com/icgc-argo/platform-ui/pull/2065
- https://github.com/icgc-argo/platform-ui/pull/2057
- https://github.com/icgc-argo/platform-ui/pull/2053
> uikit version bump

- components/pages/Homepage/index.tsx
Homepage text changes for data release
> Cherry pick/hotfix data release

- components/pages/submission-system/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTableLegend.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/InvalidDonorsNotification.tsx
* Styling changes to the table legend based on feedback
* Updated wording for Invalid Donor alert
> 💄 Donor Dashboard Table Legend UI Updates (#2042)

- uikit/Footer/index.tsx
Replaces static '2020' w/ dynamic value of current year
> 💄 Make Footer Year Dynamic #2102

- components/pages/submission-system/program-dashboard/ClinicalChart/Legend.tsx
- components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/mockData.ts
- components/pages/submission-system/program-dashboard/ClinicalChart/types.ts
- components/pages/submission-system/program-dashboard/ClinicalChart/utils.ts
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.gql
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
* Adds new `Open Access VF` column to Donor Dashboard Summary Table
* Add filtering for open access workflows to table
> ✨ Add Open Access VF Column and Filtering to Donor Summary Table (#2063)

- components/pages/Homepage/index.tsx
- global/constants/docSitePaths.tsx
Fixes broken 'About Our Workflows' link on homepage, updates '1.1.2' text to '1.1.3'
> Fix homepage links and content

- components/pages/file-repository/charts/DataTypesChart/index.tsx
- components/pages/file-repository/charts/ProgramBarChart/index.tsx
- components/pages/file-repository/charts/SimpleBarChart/index.tsx
- components/pages/file-repository/index.tsx
Click on Data Type / # of files/program bar charts will add that field/value to filters
> Make Charts Interactive

- global/utils/common.tsx
- pages/_app.tsx
- encode URL for login redirects
- use constant for `isOauth`
> #2004 - login from file entity page

- Jenkinsfile.groovy
> remove uikit steps from jenkins

- components/pages/file-entity/FILE_ENTITY_QUERY.gql
- components/pages/file-entity/FileTitleBar.tsx
- components/pages/file-entity/index.tsx
- components/pages/file-entity/types.tsx
- components/pages/file-entity/useEntityData.tsx
- components/pages/file-repository/utils/constants.tsx
Adds a tag to the file entity page when the file belongs to a private access tier
> 💄 #2148 File Entity Private Access Tag

- components/pages/file-entity/FileSummary/index.tsx
Rearrange the conditions surrounding the Program Name record in the File Entity page summary table
- [ x No changes to UI
> 🐛 Prevent Showing 'undefined' Program Name for Unauthenticated Users (#2105)

- components/pages/file-repository/FacetPanel/SEARCH_BY_QUERY.gql
- components/pages/file-repository/FacetPanel/SearchResultsMenu.tsx
- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/FacetPanel/types.ts
- components/pages/file-repository/FileTable/index.tsx
Updates file facet search to display file id, study id, & data category
Applies file id filter to SQon when searching files
Sorts file table by file id
> 💄 #2155 New Search Text

- components/pages/file-entity/index.tsx
- components/pages/file-entity/useEntityData.tsx
Persists query data to the front end for files which contain errors, page renders normally
Logs file errors to console
> 🐛 #2149 Handle Broken File Entity Queries

- components/pages/file-repository/QueryBar/index.tsx
- package-lock.json
- package.json
Updating the Arranger components package, in order to remove an existing vulnerability.
No changes should be noticeable in existing functionality, and no new features have been added.
> update Arranger components version - 3.0.0-beta.3

- components/pages/file-entity/FileTitleBar.tsx
* Use `downloadFileWithEgoToken` for download to be consistent with File Repository manifest download
- [ x Feature is minimally responsive
> 🐛 Update File Manifest Download on File Entity Page (#2147)

- pages/_app.tsx
- refactor app.tsx to hooks
- will be refactoring more in the next ticket - all this does is convert the class component `Root` to a functional component that uses hooks.
- the biggest change is that getInitialProps is now below the component declaration
> (#2175) refactor app.tsx to hooks

- components/pages/file-repository/FileTable/index.tsx
- components/pages/file-repository/utils/constants.tsx
Sorts File Table by File ID ascending
Updates TSV File download columns order to reflect File Table columns
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2109
> 💄 #2109 Update File ID Orders

- components/pages/file-entity/DataAndAnalysis/index.tsx
- components/pages/file-entity/dummyData.tsx
- components/pages/file-entity/types.tsx
Displays multiple analysis tool entries as a comma + space separated sentence
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2178
> 🐛 #2178 Proper Analysis Tools Concatenation

- components/pages/file-entity/DataAndAnalysis/index.tsx
Replaces 'null' fields with '--' on the file entity page
> 🐛 #2170 Handle File Entity null values

- components/pages/file-entity/FileTitleBar.tsx
- uikit/Button/index.tsx
- uikit/DropdownButton/index.tsx
- uikit/Legend/index.tsx
- uikit/Legend/stories.tsx
Updates Legend Component to use UI Kit component
Fixes menu behaviour to open on hover + 'enter' key but not on click
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/uikit/25
- [ x Feature is minimally responsive
> 💄 #25 Legend Component Update

- components/pages/user/ApiTokenBox/index.tsx
- components/pages/user/index.tsx
- pages/user/index.tsx
Checks JWT for Scopes to determine whether user can generate a token
> 🐛 #1794 Update Profile Token Generation Logic

- package-lock.json
- package.json
* 📦️ Upgrade `filesize` package to fix a bug where file size conversions would be slightly incorrect
> 🐛 Fix Inconsistencies Displaying File Sizes (#2184)

- components/pages/file-repository/FacetPanel/index.tsx
* Tabs even width
* Hover state moved to non-active tab
* Hides horizontal scrollbar
> 💄 #2156 facet tab edits

- components/pages/file-entity/SequencingReadProperties/index.tsx
* Evenly space items in Sequencing Read Properties sections
> 💄 Update spacing for `Sequencing Read Properties` (#2219)

- components/pages/donor-entity/ClinicalTimeline/Timeline.tsx
- components/pages/donor-entity/ClinicalTimeline/index.tsx
- components/pages/donor-entity/DonorCardsLayout.tsx
- components/pages/donor-entity/DonorDataTable/index.tsx
- components/pages/donor-entity/DonorFileCard/index.tsx
- components/pages/donor-entity/DonorTitleBar.tsx
- components/pages/donor-entity/dummyData.tsx
[#2242 
](https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2242)
* Equal card spacing & height
* Maintain spaces between tables
* Prevent crash on 'Deceased'
* Fix Clinical Timeline right margin
* Add Timeline Item Hover State
* Top align Interval header
* Timeline-card height fits content
* Remove specimen left indent
* Show full-length multiline values
* Center timeline dot
* Add Data Dictionary Link
> 💄 Donor Entity Layout Updates

- components/pages/donor-entity/ClinicalTimeline/Timeline.tsx
- components/pages/donor-entity/ClinicalTimeline/index.tsx
- components/pages/donor-entity/DonorCardsLayout.tsx
- components/pages/donor-entity/DonorDataTable/index.tsx
- components/pages/donor-entity/DonorFileCard/index.tsx
- components/pages/donor-entity/DonorTitleBar.tsx
- components/pages/donor-entity/dummyData.tsx
- components/pages/file-repository/FileTable/TsvDownloadButton.tsx
- components/pages/file-repository/FileTable/index.tsx
- package-lock.json
- package.json
Donor Entity Layout Feedback #2242 
PR: https://github.com/icgc-argo/platform-ui/pull/2251
#521 Default Blue Descending Header Band
PR: https://github.com/icgc-argo/platform-ui/pull/2250
#2241 Prevent Loading on Selected File # Click
PR: https://github.com/icgc-argo/platform-ui/pull/2249
Update spacing for Sequencing Read Properties (#2219)
PR: https://github.com/icgc-argo/platform-ui/pull/2248
> 🚀 Rc/1.106.3

- components/pages/donor-entity/dummyData.tsx
- components/pages/file-entity/FileSummary/index.tsx
- components/pages/file-entity/dummyData.tsx
- components/pages/file-entity/types.tsx
- components/pages/file-entity/useEntityData.tsx
Add file_name to the File Summary Table on the File Entity page.
> ✨ #2255: add file name to file entity page

- components/pages/team.tsx
> 💬 #2113: update team page v3

- components/pages/file-entity/DataAndAnalysis/index.tsx
Updates File Entity page 'Genome Build' Copy & URL
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2288
- [] No changes to UI
> 🧹 #2288 Make Genome Build Value more Specific

- package-lock.json
- pages/submission/program/[shortName]/clinical-submission.tsx
* Fixes 404 page visiting /${program}/clinical-submission
> 🐛 Restore clinical-submission pages file

- components/pages/Homepage/common.tsx
- components/pages/Homepage/index.tsx
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2318
- updated Announcements
- refactor component to make HTML more semantic and DRY
- add `<h3>`, use `<p>` inside `<div>`
- resolve console error about `<div>` inside a `<p>`
> 🎨 💬 2318: update announcements

- components/pages/Homepage/index.tsx
> Hotfix: Updated Software Version Numbers

- pages/submission/program/[shortName]/clinical-data.tsx
Adds 404 Page handler when Feature Submitted Data flag is set to 'false'
> Hotfix: Submitted Data Feature Flag Handling

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
- pages/submission/program/[shortName]/clinical-data.tsx
Patch submitted data feature flag + home page software versions
> RC 1.110.1

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
Resets Page counter to 0 when PageSize changes
Prevents bugs caused by queries for non-existent pages/documents
Majority of bug fixes related to ticket are here:
https://github.com/icgc-argo/argo-clinical/compare/develop...feat/2340-fix-pagination
Issue #2340 
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2340
> 📄 #2340 Fix Pagination

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
Handles files w/ errors + sorting by core completion columns
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2265
> ⏬ #2265 Entity Data table sort

- components/pages/file-repository/FileTable/index.tsx
- show partial data when there's an issue with requests in the File Repo table
- show errors in the console
> #2365: improve error handling on File Repo table

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- package-lock.json
- package.json
#2340 Fix Submitted Data Pagination
#2265 Updates Submitted Data Sorting
> 🛸 RC 1.111.2

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
(https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/argo-clinical/790) Submitted Core Completeness Table Updates
- Renders checkmarks where CoreCompletion === 1
> ✅  #790 Core Completion - Render Checkmarks

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- components/pages/submission-system/program-submitted-data/SearchBar/index.tsx
- components/pages/submission-system/program-submitted-data/index.tsx
* Updates Submitted Data display text + query filter based on completion state dropdown value
Argo-Clinical PR: https://github.com/icgc-argo/argo-clinical/pull/806
> 📁 #2268 Submitted Data Quick Filters

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
Counts # of Affected Records related to Error w/ given Donor ID + Field
Covers Missing Field + 'Invalid By Script' missing field errors
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2385
> 🪰  #2385 Submitted Data Error Count Inconsistencies

- components/pages/submission-system/program-dashboard/ClinicalChart/Legend.tsx
- components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
- components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/mockData.ts
- components/pages/submission-system/program-dashboard/ClinicalChart/types.ts
- components/pages/submission-system/program-dashboard/ClinicalChart/utils.ts
- components/pages/submission-system/program-dashboard/index.tsx
- add RNA fields to molecular chart (Alexi's API PR: https://github.com/icgc-argo/platform-api/pull/580)
- this was partially implemented but needed some updates (`key` needs to be field not title, due to conflicts)
- fix styling issue where molecular chart was a bit taller than the one beside it
- update mock data
> #2198: add RNA to molecular chart

- .github/pull_request_template.md
- update PR template
- add back-end section
- add more options for PR types
- remove manual testing; should be a given
> #2386: update PR template

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx
- rename RNA table columns
- rename RNA filter parameters
- change filter names to from `Title Casing` to `Sentence casing` for consistency
> #2246: RNA table filters

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
- update filters in Donor Summary Table on the Program Dashboard
related back end PRs:
- https://github.com/icgc-argo/platform-api/pull/614
- https://github.com/icgc-argo/platform-api/pull/611
> #2245: DNA filters in Donor Summary Table

- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.ts
- generated/gql_types.tsx
- add graphql types
- add DNA filters to graphql request
> #2245: DNA filters - fix bugs

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- components/pages/submission-system/program-submitted-data/SearchBar/index.tsx
- components/pages/submission-system/program-submitted-data/index.tsx
* Updates DonorID + SubmitterID regex w/ comments
* Fixes displayed result counts
* Displays No Data state
* Adds 'records' copy to table
Related Service PR: https://github.com/icgc-argo/argo-clinical/pull/829
> 🕷️ #2415 Submitted Data Search Bar Bugs

- package-lock.json
- package.json
> chore: update uikit

- .husky/pre-commit
- .husky/pre-push
- .huskyrc
- package-lock.json
- package.json
upgrades Husky to latest version and config 
not sure if you have a ticket assigned for this already @samrichca  https://github.com/icgc-argo/platform-ui/pull/2305#issuecomment-1155531342
> Upgrade Husky and fix hooks

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- Adds more descriptive error text for error type 'UNRECOGNIZED_FIELD'
> 🐛 #789 Submitted Data - Unrecognized Field Error Message

- package-lock.json
- package.json
> Chore/ Merge back 1.115

- components/pages/donor-entity/ClinicalTimeline/Timeline.tsx
- components/pages/donor-entity/ClinicalTimeline/util.tsx
- global/utils/common.tsx
- package-lock.json
- remove logic that shows age as ">=90"
- retain logic that caps age at 90 just in case
> #2349: update formatting for ages 90+

- components/pages/donor-entity/ClinicalTimeline/Timeline.tsx
- components/pages/donor-entity/ClinicalTimeline/util.tsx
- global/utils/common.tsx
- remove formatting for age 90+, assume age is capped at 90 in backend
> #2349: remove formatting for age 90+

- components/NavBar.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- package-lock.json
- package.json
- revert error styling for Program Donor Summary Table
- update Uikit to 2.1.2
- fix mobile nav button that broke in Uikit v2 (from this PR https://github.com/icgc-argo/platform-ui/pull/2429)
> Hotfix: rc/1.115.1

- components/NavBar.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- package-lock.json
- package.json
- fix desktop user dropdown button
- fix submitted data feature flag (see: https://github.com/icgc-argo/platform-ui/pull/2400/files https://github.com/icgc-argo/platform-ui/pull/2420)
> Hotfix: rc/1.115.2

- components/NavBar.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- package-lock.json
- package.json
- add changes from 1.115.2 to address merge conflicts
- FEATURE_SUBMITTED_DATA_ENABLED flag added
- revert error styling for Donor Summary Table
- fix nav dropdown button
- update uikit
1.115.2 mergeback PR https://github.com/icgc-argo/platform-ui/pull/2466
> Chore: patches from 1.115.2

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx
- package-lock.json
- update filters for RNA registered sample
- move the user to page 0 when they update table filters
- update pagination when table queries are completed
- clean up useTheme() so it's only called once
> #2460: fix RNA registered samples bugs

- components/pages/submission-system/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DesignationCell.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTableLegend.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.ts
- add errors for missing matched pairs, samples, and raw reads
- add errors to legend
> #2448: re-style error states for Donor Summary Table

- components/pages/submission-system/program-clinical-submission/PageContent.tsx
- change default tab to 'donor' on Submit Data table
> #2431: fix submit data table

- components/pages/submission-system/program-submitted-data/SearchBar/index.tsx
- package-lock.json
- package.json
Close dropdown menu on enter. 
> #2416 fix/close dropdown menu on pressing enter key

- components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
- components/pages/submission-system/program-sample-registration/Instructions/index.tsx
- generated/gql_types.tsx
- package-lock.json
Edit text to reflect the sequence of instruction in both the register-samples and submit-clinical-data pages
Register Samples Page:
Submit Clinical Data Page:
> Issue#2449: UI Updates On Action Cards in Registered Sample and Submit Clinical Data

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- components/pages/submission-system/program-submitted-data/DownloadButtons.tsx
- components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
- components/pages/submission-system/program-submitted-data/SearchBar/index.tsx
- components/pages/submission-system/program-submitted-data/SearchBar/style.tsx
- components/pages/submission-system/program-submitted-data/common.tsx
- components/pages/submission-system/program-submitted-data/index.tsx
* x button clears search results and filters
* Clear Filters button updated
* Adds Disabled state to Search Bar and Quick Filters when filtered by single Donor Id
* Prevents "No Results" found state + random text search showing filtered result
* Fixes issues with TSV download buttons
* Updates side menu to accurately reflect current filters (i.e. only show relevant clinical entities / alerts when filtered for current donor)
* Updates table behaviour to persist data selected by URL param filters when using search box & no results are returned
Bugs in ticket not fixed in this PR:		
* Missing Dashboard DATA-CA alerts - Fixed in QA
* 'List' button not opening modal - Working in Dev
- spelling has been …
> 🪰 #2440 Submitted Data Search + Filter feedback

- codegen.yml
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTableLegend.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/common.tsx
- components/pages/submission-system/program-dashboard/DonorDataSummary/gql/PROGRAM_DONOR_SUMMARY_QUERY.ts
- components/pages/submission-system/program-dashboard/DonorDataSummary/types.tsx
- components/pages/submission-system/program-dashboard/common.tsx
- generated/gql_types.tsx
- update text for errors (add "DNA")
- prioritize matched pairs error over raw reads error
- added new stat to API for this https://github.com/icgc-argo/platform-api/pull/636
- add filter for missing raw reads
> #2489: donor table error feedback

- components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
Feedback from BA regarding instructions in filter modal.
Implement text changes as follow:
> Issue#2510 Edit Instruction Text in Filter Modal

- package-lock.json
- package.json
- upgrade nextjs to the last 12.x version
- audit other dependencies
- update query-string to get security update for decode-uri-component
> #2506 - upgrade next

- components/SQONView/index.js
- components/pages/file-repository/QueryBar/index.tsx
- package-lock.json
- package.json
- replace recompose with hooks
> #2508 - sqonview without recompose

- components/pages/Homepage/index.tsx
- package-lock.json
- add announcement for version 1.119.0
- remove old announcement
> #2531: 1.119.0 announcement

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
Insures Submitted Data is always querying latest data from DB
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2551
> #2251 🐛 Update Query Cache Policy

- components/pages/submission-system/program-submitted-data/index.tsx
Updates Side Menu query logic
- Populates w/ selected URL donorIDs first, then uses SearchResults, otherwise does not specify donor IDs (empty array)
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2554
> 🐛 #2554 Fix Partial Search

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
> Mergeback 1.119.1

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2547
* Updates Table Error Cell logic to highlight fields with specific values
* Also updates error + record count logic for accurate numbers
> ❌ #2547 Updated Error Highlight Logic

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
* Separates Default Donor sort logic (by core completion percentage) from default entity page sort values (donorId)
Depends on + Relates to changes on Argo Clinical:
https://github.com/icgc-argo/argo-clinical/pull/904/files
> 🐞 #2546 Fix Sort by Donor ID

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- components/pages/submission-system/program-submitted-data/index.tsx
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2580
- Updates Tooltip Copy
- Displays # Specimens in Red when Samples > Specimens
> 💄 #2580 Updated CoreCompletion Specimen Details

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/gql/CLINICAL_ENTITY_DATA_QUERY.ts
Remove FamilyHistory from Submitted Data query
> Remove Core Completion Family History

- components/pages/submission-system/program-submitted-data/index.tsx
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2607
Straightens out logic surrounding `.length >= 0`
Updates variable names
Updates Search Result DonorId logic
> 🐛 #2607 Donor ID Filter Returns Incorrect Results

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- package-lock.json
- package.json
- Revise Normal/Tumour Stats after Clinical Core Completion Updates
https://github.com/icgc-argo/platform-ui/pull/2622
> RC 1.122.1

- components/pages/Homepage/index.tsx
Updates Data Release Bar header w/ correct copy
Adds news stories for Data Release 6 / RNA Seq Alignment, + Submitted Data / Program Exceptions
https://github.com/icgc-argo/platform-ui/issues/2630
> 🧹 #2630 Announcement: Data Release 6

- package-lock.json
- package.json
- Fix Specimen Column Values (https://github.com/icgc-argo/platform-ui/pull/2633)
> RC 1.122.3

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
Handles case where coreCompletion records are empty
Related to Specimen core completion changes
Steps to reproduce bug in ticket: [#2638](https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2638)
> 🐛 #2638 Handle Empty CompletionRecord

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
- package-lock.json
- package.json
#2639 Handle Empty CoreCompletion record #2638
> Rc / 1.122.4

- components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
- small refactor of donor summary table sorting to add types and reduce duplication
- update comments
> #2567 - update donor summary sorting

- components/pages/Homepage/index.tsx
Updates homepage Announcement copy + date
> Update Homepage Announcement

- components/pages/Homepage/index.tsx
> add doc link to homepage announcement

- components/pages/Homepage/index.tsx
- components/pages/program-entity/ProgramCardsLayout/index.tsx
- components/pages/program-entity/gql/PROGRAM_SUMMARY_QUERY.ts
- components/pages/program-entity/index.tsx
- components/pages/program-entity/type.tsx
- package-lock.json
- package.json
- Update Homepage Announcement
https://github.com/icgc-argo/platform-ui/pull/2656
- Connect Program Entity to Gateway
https://github.com/icgc-argo/platform-ui/pull/2627
> RC 1.122.6

- components/pages/submission-system/program-submitted-data/index.tsx
Fixes Submitted Data Side Menu donorId handling to fix queries for large programs
https://github.com/icgc-argo/argo-clinical/issues/973
> 🪰 #973 Handle Empty Search Keyword

- components/pages/submission-system/program-submitted-data/SearchBar/index.tsx
Separates search menu display items (which are concatenated at 20 items) from all search results so display counts are accurate
https://github.com/icgc-argo/platform-ui/issues/2652
> 🐛 #2652 Fuzzy Search Results Do Not Match Text

- components/pages/Homepage/index.tsx
- components/pages/program-entity/ProgramCardsLayout/index.tsx
- components/pages/program-entity/gql/PROGRAM_SUMMARY_QUERY.ts
- components/pages/program-entity/index.tsx
- components/pages/program-entity/type.tsx
- package-lock.json
- package.json
[#973](https://github.com/icgc-argo/argo-clinical/issues/973) Handle Empty Search Keyword Bug 
PR: https://github.com/icgc-argo/platform-ui/pull/2662
#2652 Fuzzy Search Results Do Not Match Text
PR: https://github.com/icgc-argo/platform-ui/pull/2665
> RC / 1.122.7

- pages/program/[programId].tsx
Fixes program entity page to work correctly when feature is enabled.
> User Program Feature Flag in Program Page

- components/pages/program-entity/ProgramCardsLayout/util.tsx
- components/pages/program-entity/gql/DONOR_AND_FILE_COUNT_TABLES_QUERY.ts
- package.json
* Correct feature flags to enable program entity page
> Release Candidate 1.123.1

- components/pages/Homepage/index.tsx
> add Quicksilver announcement

- components/pages/program-entity/ProgramCardsLayout/util.tsx
- components/pages/program-entity/gql/DONOR_AND_FILE_COUNT_TABLES_QUERY.ts
- package-lock.json
- package.json
* Home page notifications for release
> Release Candidate 1.123.2

- components/pages/submission-system/program-submitted-data/DownloadButtons.tsx
- Use POST Body + application/json header for clinical data download requests
> Fix Clinical Data Downloads

- components/pages/submission-system/program-submit-clinical/index.tsx
- Updates Headline font color
- Adds padding between globe icon + headline text
> 💄  #1002 Submit Clinical CSS Tweaks

- components/pages/Homepage/index.tsx
> rocket racoon update version text

- components/pages/Homepage/index.tsx
> updaet homepage announcements

- global/constants/gatewayApiPaths.tsx
Update template download URL to match changed proxy paths from platform-api.
> Include `/proxy` in clinical template download URL

- components/pages/Homepage/index.tsx
Updated copy for Storm release
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2723
> #2723 Updated Storm Release Notes

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
- Correct text formatting from markdown to JSX on release announcement
> Hotfix - Fix Announcement Link

- components/pages/Homepage/index.tsx
- components/pages/submission-system/SideMenu.tsx
- package-lock.json
- package.json
- pages/submission/program/[shortName]/manage.tsx
* Allow DCC Admins to access manage program page
* Clinical data announcement
* Versioning 1.125.1
> Merge Back - Master @ 1.125.1

- README.md
> :memo: updates readme portion about uikit

- components/pages/Homepage/index.tsx
Updates Homepage Link copy for latest Data + Software release
> 🧹  Data Release 7 + Software Release 1.125.1 / 3.42.0 Link Updates

- components/pages/Homepage/common.tsx
- components/pages/Homepage/index.tsx
- generated/gql_types.tsx
- package-lock.json
bonus, re-syncs outdated:
- manifest lock
- graphql type definitions
> improve recent announcements

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
Announcement text to accompany RDPC Migration to cumulus.
> Hotfix - Announcement text for RDPC migration

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
> nov 30 announcement hotfix mergeback

- components/pages/file-repository/FacetPanel/index.tsx
- components/pages/file-repository/FileTable/index.tsx
- Populates ObjectId values when all files are selected
- Tested w/ Dev (2 files) + QA (2400+ files) Data 
> 🐜 #1056 Fix Select All Clinical Download

- components/pages/submission-system/program-form/ProgramForm.tsx
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/roadmap/1098
Adds data center id as default form value
Data Center dropdown Placeholder changes depending on view - Create Program (shows default message) vs Manage Program (shows current Data Center)
> 👾 #1098 Update Program data center fixes

- components/pages/Homepage/index.tsx
> add announcement. remove old one

- components/pages/Homepage/index.tsx
> update april announcement

- components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-ui/2624
Sorts Invalid Records to the top of the Submitted Data table on first page load
examples shown in ticket
> ↕️ Submitted Data: Sort Invalid Donors First

- components/pages/Homepage/index.tsx
> May release announcement updates

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
> Main mergeback 1.125.8

- components/pages/Homepage/index.tsx
- Add Sept data release 10 homepage announcement
- Removes oldest announcement
> data release 10 homepage announcement

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
- remove April announcement
- add data release 11 announcement
> add data release 11 announcement

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
* add data release 11 announcement
---------
> Merge back - main @ 1.126.0

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
> Main mergeback 1.126.1

- components/NavBar.tsx
- components/pages/discovery/index.tsx
- global/constants/pages.tsx
- package-lock.json
- package.json
- pages/discovery/index.tsx
Adds page and routing for Data Discovery 
> Add Data Discovery page and route

- components/pages/file-repository/FileTable/TsvDownloadButton.tsx
- package-lock.json
- package.json
- https://github.com/icgc-argo/platform-ui/pull/2793
> Release Candidate 1.127.0

- components/pages/discovery/components/Facets/FacetStateProvider.tsx
- components/pages/discovery/components/Facets/Search.tsx
- components/pages/discovery/components/Facets/index.tsx
Basic toggle for expand/collapse all UI facet
> cleanup toggle

- charts/Chart.tsx
- charts/Doughnut/index.tsx
- charts/arranger.ts
- charts/types.ts
- components/pages/discovery/Charts.tsx
- components/pages/discovery/charts/Bar.tsx
- components/pages/discovery/charts/Doughnut.tsx
- components/pages/discovery/charts/Line.tsx
- components/pages/discovery/charts/common.tsx
provide chart loaders and error states
- individual isolated to components in card
- full page loader requires building out a higher level provider to group loading states
> provide chart loaders and error states

- components/pages/discovery/components/Facets/RangeFacet.tsx
[target only button element for toggle facet folder](https://github.com/icgc-argo/platform-ui/commit/e21501c0133d24ebf4af274804d0ae4c8e3a5b43)
> target only button element for toggle facet folder

- components/pages/discovery/Charts.tsx
> update age-at-diagnosis labels

- components/pages/discovery/Charts.tsx
> remove rdpc node chart

- charts/Chart.tsx
- charts/Doughnut/data.tsx
- charts/Doughnut/index.tsx
- charts/Doughnut/ui.tsx
- charts/NoData.tsx
- charts/types.ts
- components/pages/discovery/Charts.tsx
- components/pages/discovery/charts/Doughnut.tsx
- components/pages/discovery/components/Facets/RangeFacet/FacetMenuItem.tsx
- components/pages/discovery/components/Facets/RangeFacet/RangeFacet.tsx
- components/pages/discovery/components/Facets/index.tsx
- components/pages/discovery/index.tsx
- global/utils/arrangerFilter/filter.test.tsx
- global/utils/arrangerFilter/index.tsx
- package-lock.json
- package.json
- testNullCompiler.js
- Fix cases of facets not rendering on updates https://github.com/icgc-argo/platform-ui/pull/2823
- update age_at_diagnosis labels https://github.com/icgc-argo/platform-ui/pull/2825
- remove RDPC node chart https://github.com/icgc-argo/platform-ui/pull/2826
- filtering from sunburst - https://github.com/icgc-argo/platform-ui/pull/2827
- update ranges for primary_diagnosis
Sunburst chart has a lot of bespoke functionality which will be updated to the @overture-stack/charts way of doing things here: https://github.com/icgc-argo/roadmap/issues/1254
> data discovery

- components/pages/discovery/components/Facets/DISCOVERY_FACETS_QUERY.ts
- components/pages/discovery/data/facet.ts
- components/pages/discovery/index.tsx
Adds file filter facets that are available under the "Molecular" category for facets
> add file filter facets

- components/pages/discovery/Charts.tsx
https://github.com/icgc-argo/roadmap/issues/1266
fix to add in filter instead of destructive replace
> fix add in filter instead of new replacement

- components/pages/discovery/Charts.tsx
- package-lock.json
- package.json
> use latest arranger charts

- components/pages/Homepage/index.tsx
- package-lock.json
- package.json
> rc/1.133.6 

- components/pages/discovery/components/StatsCard.tsx
- components/pages/discovery/index.tsx
- add stats bar back with cardinality query
- rounds number to nearest thousand and display values with `~` for approximate if above threshold value
> add stats bar back with cardinality query
